// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/statistics/statistics.proto

package statistics

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PricesStat struct {
	Id                   uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Revenues             []float32 `protobuf:"fixed32,2,rep,packed,name=revenues,proto3" json:"revenues,omitempty"`
	Sum                  float32   `protobuf:"fixed32,3,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PricesStat) Reset()         { *m = PricesStat{} }
func (m *PricesStat) String() string { return proto.CompactTextString(m) }
func (*PricesStat) ProtoMessage()    {}
func (*PricesStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e7db84dac01a13, []int{0}
}

func (m *PricesStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PricesStat.Unmarshal(m, b)
}
func (m *PricesStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PricesStat.Marshal(b, m, deterministic)
}
func (m *PricesStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PricesStat.Merge(m, src)
}
func (m *PricesStat) XXX_Size() int {
	return xxx_messageInfo_PricesStat.Size(m)
}
func (m *PricesStat) XXX_DiscardUnknown() {
	xxx_messageInfo_PricesStat.DiscardUnknown(m)
}

var xxx_messageInfo_PricesStat proto.InternalMessageInfo

func (m *PricesStat) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PricesStat) GetRevenues() []float32 {
	if m != nil {
		return m.Revenues
	}
	return nil
}

func (m *PricesStat) GetSum() float32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

type GetPricesStatisticsByYearRequest struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPricesStatisticsByYearRequest) Reset()         { *m = GetPricesStatisticsByYearRequest{} }
func (m *GetPricesStatisticsByYearRequest) String() string { return proto.CompactTextString(m) }
func (*GetPricesStatisticsByYearRequest) ProtoMessage()    {}
func (*GetPricesStatisticsByYearRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e7db84dac01a13, []int{1}
}

func (m *GetPricesStatisticsByYearRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPricesStatisticsByYearRequest.Unmarshal(m, b)
}
func (m *GetPricesStatisticsByYearRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPricesStatisticsByYearRequest.Marshal(b, m, deterministic)
}
func (m *GetPricesStatisticsByYearRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPricesStatisticsByYearRequest.Merge(m, src)
}
func (m *GetPricesStatisticsByYearRequest) XXX_Size() int {
	return xxx_messageInfo_GetPricesStatisticsByYearRequest.Size(m)
}
func (m *GetPricesStatisticsByYearRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPricesStatisticsByYearRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPricesStatisticsByYearRequest proto.InternalMessageInfo

func (m *GetPricesStatisticsByYearRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

type GetPricesStatisticsByYearResponse struct {
	PricesStat           []*PricesStat `protobuf:"bytes,1,rep,name=prices_stat,json=pricesStat,proto3" json:"prices_stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPricesStatisticsByYearResponse) Reset()         { *m = GetPricesStatisticsByYearResponse{} }
func (m *GetPricesStatisticsByYearResponse) String() string { return proto.CompactTextString(m) }
func (*GetPricesStatisticsByYearResponse) ProtoMessage()    {}
func (*GetPricesStatisticsByYearResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e7db84dac01a13, []int{2}
}

func (m *GetPricesStatisticsByYearResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPricesStatisticsByYearResponse.Unmarshal(m, b)
}
func (m *GetPricesStatisticsByYearResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPricesStatisticsByYearResponse.Marshal(b, m, deterministic)
}
func (m *GetPricesStatisticsByYearResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPricesStatisticsByYearResponse.Merge(m, src)
}
func (m *GetPricesStatisticsByYearResponse) XXX_Size() int {
	return xxx_messageInfo_GetPricesStatisticsByYearResponse.Size(m)
}
func (m *GetPricesStatisticsByYearResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPricesStatisticsByYearResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPricesStatisticsByYearResponse proto.InternalMessageInfo

func (m *GetPricesStatisticsByYearResponse) GetPricesStat() []*PricesStat {
	if m != nil {
		return m.PricesStat
	}
	return nil
}

type ProductsStat struct {
	Id                   uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Revenues             []float32 `protobuf:"fixed32,2,rep,packed,name=revenues,proto3" json:"revenues,omitempty"`
	Sum                  float32   `protobuf:"fixed32,3,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ProductsStat) Reset()         { *m = ProductsStat{} }
func (m *ProductsStat) String() string { return proto.CompactTextString(m) }
func (*ProductsStat) ProtoMessage()    {}
func (*ProductsStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e7db84dac01a13, []int{3}
}

func (m *ProductsStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductsStat.Unmarshal(m, b)
}
func (m *ProductsStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductsStat.Marshal(b, m, deterministic)
}
func (m *ProductsStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductsStat.Merge(m, src)
}
func (m *ProductsStat) XXX_Size() int {
	return xxx_messageInfo_ProductsStat.Size(m)
}
func (m *ProductsStat) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductsStat.DiscardUnknown(m)
}

var xxx_messageInfo_ProductsStat proto.InternalMessageInfo

func (m *ProductsStat) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductsStat) GetRevenues() []float32 {
	if m != nil {
		return m.Revenues
	}
	return nil
}

func (m *ProductsStat) GetSum() float32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

type GetProductsStatisticsByYearRequest struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsStatisticsByYearRequest) Reset()         { *m = GetProductsStatisticsByYearRequest{} }
func (m *GetProductsStatisticsByYearRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductsStatisticsByYearRequest) ProtoMessage()    {}
func (*GetProductsStatisticsByYearRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e7db84dac01a13, []int{4}
}

func (m *GetProductsStatisticsByYearRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsStatisticsByYearRequest.Unmarshal(m, b)
}
func (m *GetProductsStatisticsByYearRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsStatisticsByYearRequest.Marshal(b, m, deterministic)
}
func (m *GetProductsStatisticsByYearRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsStatisticsByYearRequest.Merge(m, src)
}
func (m *GetProductsStatisticsByYearRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductsStatisticsByYearRequest.Size(m)
}
func (m *GetProductsStatisticsByYearRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsStatisticsByYearRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsStatisticsByYearRequest proto.InternalMessageInfo

func (m *GetProductsStatisticsByYearRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

type GetProductsStatisticsByYearResponse struct {
	ProductsStat         []*ProductsStat `protobuf:"bytes,1,rep,name=products_stat,json=productsStat,proto3" json:"products_stat,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetProductsStatisticsByYearResponse) Reset()         { *m = GetProductsStatisticsByYearResponse{} }
func (m *GetProductsStatisticsByYearResponse) String() string { return proto.CompactTextString(m) }
func (*GetProductsStatisticsByYearResponse) ProtoMessage()    {}
func (*GetProductsStatisticsByYearResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18e7db84dac01a13, []int{5}
}

func (m *GetProductsStatisticsByYearResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsStatisticsByYearResponse.Unmarshal(m, b)
}
func (m *GetProductsStatisticsByYearResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsStatisticsByYearResponse.Marshal(b, m, deterministic)
}
func (m *GetProductsStatisticsByYearResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsStatisticsByYearResponse.Merge(m, src)
}
func (m *GetProductsStatisticsByYearResponse) XXX_Size() int {
	return xxx_messageInfo_GetProductsStatisticsByYearResponse.Size(m)
}
func (m *GetProductsStatisticsByYearResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsStatisticsByYearResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsStatisticsByYearResponse proto.InternalMessageInfo

func (m *GetProductsStatisticsByYearResponse) GetProductsStat() []*ProductsStat {
	if m != nil {
		return m.ProductsStat
	}
	return nil
}

func init() {
	proto.RegisterType((*PricesStat)(nil), "statistics.PricesStat")
	proto.RegisterType((*GetPricesStatisticsByYearRequest)(nil), "statistics.GetPricesStatisticsByYearRequest")
	proto.RegisterType((*GetPricesStatisticsByYearResponse)(nil), "statistics.GetPricesStatisticsByYearResponse")
	proto.RegisterType((*ProductsStat)(nil), "statistics.ProductsStat")
	proto.RegisterType((*GetProductsStatisticsByYearRequest)(nil), "statistics.GetProductsStatisticsByYearRequest")
	proto.RegisterType((*GetProductsStatisticsByYearResponse)(nil), "statistics.GetProductsStatisticsByYearResponse")
}

func init() { proto.RegisterFile("proto/statistics/statistics.proto", fileDescriptor_18e7db84dac01a13) }

var fileDescriptor_18e7db84dac01a13 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x31, 0x4f, 0xfb, 0x30,
	0x10, 0xc5, 0xff, 0x71, 0xfe, 0x20, 0x74, 0x6d, 0x11, 0xdc, 0x80, 0x42, 0x58, 0x52, 0xb3, 0x64,
	0x80, 0x54, 0x2a, 0x12, 0xb0, 0xb0, 0xb0, 0x20, 0x21, 0x86, 0xca, 0x9d, 0x90, 0x90, 0x50, 0x48,
	0x6e, 0xf0, 0x40, 0x63, 0x6c, 0xa7, 0x52, 0x99, 0xf8, 0x0c, 0x7c, 0x62, 0x54, 0xb7, 0xd4, 0x41,
	0x88, 0x90, 0x81, 0xed, 0x5d, 0xf2, 0xee, 0xdd, 0xfd, 0x2e, 0x81, 0xa1, 0xd2, 0x95, 0xad, 0x46,
	0xc6, 0xe6, 0x56, 0x1a, 0x2b, 0x0b, 0xd3, 0x90, 0x99, 0x7b, 0x87, 0xe0, 0x9f, 0xf0, 0x5b, 0x80,
	0x89, 0x96, 0x05, 0x99, 0xa9, 0xcd, 0x2d, 0xee, 0x02, 0x93, 0x65, 0x14, 0x24, 0x41, 0x3a, 0x10,
	0x4c, 0x96, 0x18, 0xc3, 0x8e, 0xa6, 0x39, 0xcd, 0x6a, 0x32, 0x11, 0x4b, 0xc2, 0x94, 0x89, 0x4d,
	0x8d, 0x7b, 0x10, 0x9a, 0xfa, 0x39, 0x0a, 0x93, 0x20, 0x65, 0x62, 0x29, 0xf9, 0x39, 0x24, 0x37,
	0x64, 0x7d, 0xdc, 0x6a, 0xc4, 0xf5, 0xe2, 0x9e, 0x72, 0x2d, 0xe8, 0xa5, 0x26, 0x63, 0x11, 0xe1,
	0xff, 0x82, 0x72, 0xed, 0x66, 0x6c, 0x09, 0xa7, 0xf9, 0x03, 0x0c, 0x5b, 0xfa, 0x8c, 0xaa, 0x66,
	0x86, 0xf0, 0x02, 0x7a, 0xca, 0x39, 0x1e, 0x97, 0xdb, 0x47, 0x41, 0x12, 0xa6, 0xbd, 0xf1, 0x41,
	0xd6, 0x80, 0xf3, 0x01, 0x02, 0xd4, 0x46, 0xf3, 0x3b, 0xe8, 0x4f, 0x74, 0x55, 0xd6, 0x85, 0xfd,
	0x0b, 0xc6, 0x4b, 0xe0, 0x6e, 0x57, 0x1f, 0xd8, 0x95, 0xb2, 0x84, 0xe3, 0xd6, 0xce, 0x35, 0xe7,
	0x15, 0x0c, 0xd4, 0xda, 0xd3, 0x24, 0x8d, 0xbe, 0x92, 0xfa, 0x10, 0xd1, 0x57, 0x8d, 0x6a, 0xfc,
	0xce, 0x60, 0xdf, 0x67, 0x4f, 0x49, 0xcf, 0x65, 0x41, 0xf8, 0x0a, 0x87, 0x3f, 0x5e, 0x18, 0x4f,
	0x9a, 0xd1, 0xbf, 0x7d, 0xc0, 0xf8, 0xb4, 0xa3, 0x7b, 0x85, 0xc3, 0xff, 0xe1, 0x5b, 0x00, 0x47,
	0x2d, 0xe0, 0x98, 0x7d, 0x0b, 0x6c, 0xbd, 0x6d, 0x3c, 0xea, 0xec, 0xff, 0x5c, 0xe1, 0x69, 0xdb,
	0xfd, 0xf7, 0x67, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x36, 0x57, 0x6a, 0x0a, 0x1c, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatisticsServiceClient is the client API for StatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatisticsServiceClient interface {
	GetPricesStatisticsByYear(ctx context.Context, in *GetPricesStatisticsByYearRequest, opts ...grpc.CallOption) (*GetPricesStatisticsByYearResponse, error)
	GetProductsStatisticsByYear(ctx context.Context, in *GetProductsStatisticsByYearRequest, opts ...grpc.CallOption) (*GetProductsStatisticsByYearResponse, error)
}

type statisticsServiceClient struct {
	cc *grpc.ClientConn
}

func NewStatisticsServiceClient(cc *grpc.ClientConn) StatisticsServiceClient {
	return &statisticsServiceClient{cc}
}

func (c *statisticsServiceClient) GetPricesStatisticsByYear(ctx context.Context, in *GetPricesStatisticsByYearRequest, opts ...grpc.CallOption) (*GetPricesStatisticsByYearResponse, error) {
	out := new(GetPricesStatisticsByYearResponse)
	err := c.cc.Invoke(ctx, "/statistics.StatisticsService/GetPricesStatisticsByYear", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) GetProductsStatisticsByYear(ctx context.Context, in *GetProductsStatisticsByYearRequest, opts ...grpc.CallOption) (*GetProductsStatisticsByYearResponse, error) {
	out := new(GetProductsStatisticsByYearResponse)
	err := c.cc.Invoke(ctx, "/statistics.StatisticsService/GetProductsStatisticsByYear", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServiceServer is the server API for StatisticsService service.
type StatisticsServiceServer interface {
	GetPricesStatisticsByYear(context.Context, *GetPricesStatisticsByYearRequest) (*GetPricesStatisticsByYearResponse, error)
	GetProductsStatisticsByYear(context.Context, *GetProductsStatisticsByYearRequest) (*GetProductsStatisticsByYearResponse, error)
}

// UnimplementedStatisticsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStatisticsServiceServer struct {
}

func (*UnimplementedStatisticsServiceServer) GetPricesStatisticsByYear(ctx context.Context, req *GetPricesStatisticsByYearRequest) (*GetPricesStatisticsByYearResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPricesStatisticsByYear not implemented")
}
func (*UnimplementedStatisticsServiceServer) GetProductsStatisticsByYear(ctx context.Context, req *GetProductsStatisticsByYearRequest) (*GetProductsStatisticsByYearResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductsStatisticsByYear not implemented")
}

func RegisterStatisticsServiceServer(s *grpc.Server, srv StatisticsServiceServer) {
	s.RegisterService(&_StatisticsService_serviceDesc, srv)
}

func _StatisticsService_GetPricesStatisticsByYear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPricesStatisticsByYearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetPricesStatisticsByYear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/statistics.StatisticsService/GetPricesStatisticsByYear",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetPricesStatisticsByYear(ctx, req.(*GetPricesStatisticsByYearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_GetProductsStatisticsByYear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsStatisticsByYearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).GetProductsStatisticsByYear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/statistics.StatisticsService/GetProductsStatisticsByYear",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).GetProductsStatisticsByYear(ctx, req.(*GetProductsStatisticsByYearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatisticsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "statistics.StatisticsService",
	HandlerType: (*StatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPricesStatisticsByYear",
			Handler:    _StatisticsService_GetPricesStatisticsByYear_Handler,
		},
		{
			MethodName: "GetProductsStatisticsByYear",
			Handler:    _StatisticsService_GetProductsStatisticsByYear_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/statistics/statistics.proto",
}
