// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/svc-storage-writer/writer/svc-storage-writer.proto

package writer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	model "github.com/methrilion/gourmet/proto/model"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCurrencyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCurrencyRequest) Reset()         { *m = ListCurrencyRequest{} }
func (m *ListCurrencyRequest) String() string { return proto.CompactTextString(m) }
func (*ListCurrencyRequest) ProtoMessage()    {}
func (*ListCurrencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{0}
}

func (m *ListCurrencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCurrencyRequest.Unmarshal(m, b)
}
func (m *ListCurrencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCurrencyRequest.Marshal(b, m, deterministic)
}
func (m *ListCurrencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCurrencyRequest.Merge(m, src)
}
func (m *ListCurrencyRequest) XXX_Size() int {
	return xxx_messageInfo_ListCurrencyRequest.Size(m)
}
func (m *ListCurrencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCurrencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCurrencyRequest proto.InternalMessageInfo

type ListCurrencyResponse struct {
	Currency             []*model.Currency `protobuf:"bytes,1,rep,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListCurrencyResponse) Reset()         { *m = ListCurrencyResponse{} }
func (m *ListCurrencyResponse) String() string { return proto.CompactTextString(m) }
func (*ListCurrencyResponse) ProtoMessage()    {}
func (*ListCurrencyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{1}
}

func (m *ListCurrencyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCurrencyResponse.Unmarshal(m, b)
}
func (m *ListCurrencyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCurrencyResponse.Marshal(b, m, deterministic)
}
func (m *ListCurrencyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCurrencyResponse.Merge(m, src)
}
func (m *ListCurrencyResponse) XXX_Size() int {
	return xxx_messageInfo_ListCurrencyResponse.Size(m)
}
func (m *ListCurrencyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCurrencyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCurrencyResponse proto.InternalMessageInfo

func (m *ListCurrencyResponse) GetCurrency() []*model.Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

type CreateCurrencyRequest struct {
	Payload              *model.Currency `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateCurrencyRequest) Reset()         { *m = CreateCurrencyRequest{} }
func (m *CreateCurrencyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCurrencyRequest) ProtoMessage()    {}
func (*CreateCurrencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{2}
}

func (m *CreateCurrencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCurrencyRequest.Unmarshal(m, b)
}
func (m *CreateCurrencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCurrencyRequest.Marshal(b, m, deterministic)
}
func (m *CreateCurrencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCurrencyRequest.Merge(m, src)
}
func (m *CreateCurrencyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCurrencyRequest.Size(m)
}
func (m *CreateCurrencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCurrencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCurrencyRequest proto.InternalMessageInfo

func (m *CreateCurrencyRequest) GetPayload() *model.Currency {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ListRatesOfExchangeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRatesOfExchangeRequest) Reset()         { *m = ListRatesOfExchangeRequest{} }
func (m *ListRatesOfExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*ListRatesOfExchangeRequest) ProtoMessage()    {}
func (*ListRatesOfExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{3}
}

func (m *ListRatesOfExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRatesOfExchangeRequest.Unmarshal(m, b)
}
func (m *ListRatesOfExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRatesOfExchangeRequest.Marshal(b, m, deterministic)
}
func (m *ListRatesOfExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRatesOfExchangeRequest.Merge(m, src)
}
func (m *ListRatesOfExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_ListRatesOfExchangeRequest.Size(m)
}
func (m *ListRatesOfExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRatesOfExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRatesOfExchangeRequest proto.InternalMessageInfo

type ListRatesOfExchangeResponse struct {
	RatesOfExchange      []*model.RateOfExchange `protobuf:"bytes,1,rep,name=rates_of_exchange,json=ratesOfExchange,proto3" json:"rates_of_exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ListRatesOfExchangeResponse) Reset()         { *m = ListRatesOfExchangeResponse{} }
func (m *ListRatesOfExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*ListRatesOfExchangeResponse) ProtoMessage()    {}
func (*ListRatesOfExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{4}
}

func (m *ListRatesOfExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRatesOfExchangeResponse.Unmarshal(m, b)
}
func (m *ListRatesOfExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRatesOfExchangeResponse.Marshal(b, m, deterministic)
}
func (m *ListRatesOfExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRatesOfExchangeResponse.Merge(m, src)
}
func (m *ListRatesOfExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_ListRatesOfExchangeResponse.Size(m)
}
func (m *ListRatesOfExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRatesOfExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRatesOfExchangeResponse proto.InternalMessageInfo

func (m *ListRatesOfExchangeResponse) GetRatesOfExchange() []*model.RateOfExchange {
	if m != nil {
		return m.RatesOfExchange
	}
	return nil
}

type CreateRateOfExchangeRequest struct {
	Payload              *model.RateOfExchange `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateRateOfExchangeRequest) Reset()         { *m = CreateRateOfExchangeRequest{} }
func (m *CreateRateOfExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRateOfExchangeRequest) ProtoMessage()    {}
func (*CreateRateOfExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{5}
}

func (m *CreateRateOfExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRateOfExchangeRequest.Unmarshal(m, b)
}
func (m *CreateRateOfExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRateOfExchangeRequest.Marshal(b, m, deterministic)
}
func (m *CreateRateOfExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRateOfExchangeRequest.Merge(m, src)
}
func (m *CreateRateOfExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRateOfExchangeRequest.Size(m)
}
func (m *CreateRateOfExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRateOfExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRateOfExchangeRequest proto.InternalMessageInfo

func (m *CreateRateOfExchangeRequest) GetPayload() *model.RateOfExchange {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ListLocationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLocationsRequest) Reset()         { *m = ListLocationsRequest{} }
func (m *ListLocationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListLocationsRequest) ProtoMessage()    {}
func (*ListLocationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{6}
}

func (m *ListLocationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLocationsRequest.Unmarshal(m, b)
}
func (m *ListLocationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLocationsRequest.Marshal(b, m, deterministic)
}
func (m *ListLocationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLocationsRequest.Merge(m, src)
}
func (m *ListLocationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListLocationsRequest.Size(m)
}
func (m *ListLocationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLocationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLocationsRequest proto.InternalMessageInfo

type ListLocationsResponse struct {
	Locations            []*model.Location `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListLocationsResponse) Reset()         { *m = ListLocationsResponse{} }
func (m *ListLocationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListLocationsResponse) ProtoMessage()    {}
func (*ListLocationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{7}
}

func (m *ListLocationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLocationsResponse.Unmarshal(m, b)
}
func (m *ListLocationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLocationsResponse.Marshal(b, m, deterministic)
}
func (m *ListLocationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLocationsResponse.Merge(m, src)
}
func (m *ListLocationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListLocationsResponse.Size(m)
}
func (m *ListLocationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLocationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListLocationsResponse proto.InternalMessageInfo

func (m *ListLocationsResponse) GetLocations() []*model.Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

type CreateLocationRequest struct {
	Payload              *model.Location `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateLocationRequest) Reset()         { *m = CreateLocationRequest{} }
func (m *CreateLocationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateLocationRequest) ProtoMessage()    {}
func (*CreateLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{8}
}

func (m *CreateLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateLocationRequest.Unmarshal(m, b)
}
func (m *CreateLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateLocationRequest.Marshal(b, m, deterministic)
}
func (m *CreateLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateLocationRequest.Merge(m, src)
}
func (m *CreateLocationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateLocationRequest.Size(m)
}
func (m *CreateLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateLocationRequest proto.InternalMessageInfo

func (m *CreateLocationRequest) GetPayload() *model.Location {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ListProductsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductsRequest) Reset()         { *m = ListProductsRequest{} }
func (m *ListProductsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProductsRequest) ProtoMessage()    {}
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{9}
}

func (m *ListProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsRequest.Unmarshal(m, b)
}
func (m *ListProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsRequest.Marshal(b, m, deterministic)
}
func (m *ListProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsRequest.Merge(m, src)
}
func (m *ListProductsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProductsRequest.Size(m)
}
func (m *ListProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsRequest proto.InternalMessageInfo

type ListProductsResponse struct {
	Products             []*model.Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListProductsResponse) Reset()         { *m = ListProductsResponse{} }
func (m *ListProductsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProductsResponse) ProtoMessage()    {}
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{10}
}

func (m *ListProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsResponse.Unmarshal(m, b)
}
func (m *ListProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsResponse.Marshal(b, m, deterministic)
}
func (m *ListProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsResponse.Merge(m, src)
}
func (m *ListProductsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProductsResponse.Size(m)
}
func (m *ListProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsResponse proto.InternalMessageInfo

func (m *ListProductsResponse) GetProducts() []*model.Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type CreateProductRequest struct {
	Payload              *model.Product `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{11}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetPayload() *model.Product {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ListPricesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPricesRequest) Reset()         { *m = ListPricesRequest{} }
func (m *ListPricesRequest) String() string { return proto.CompactTextString(m) }
func (*ListPricesRequest) ProtoMessage()    {}
func (*ListPricesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{12}
}

func (m *ListPricesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPricesRequest.Unmarshal(m, b)
}
func (m *ListPricesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPricesRequest.Marshal(b, m, deterministic)
}
func (m *ListPricesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPricesRequest.Merge(m, src)
}
func (m *ListPricesRequest) XXX_Size() int {
	return xxx_messageInfo_ListPricesRequest.Size(m)
}
func (m *ListPricesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPricesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPricesRequest proto.InternalMessageInfo

type ListPricesResponse struct {
	Prices               []*model.Price `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListPricesResponse) Reset()         { *m = ListPricesResponse{} }
func (m *ListPricesResponse) String() string { return proto.CompactTextString(m) }
func (*ListPricesResponse) ProtoMessage()    {}
func (*ListPricesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{13}
}

func (m *ListPricesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPricesResponse.Unmarshal(m, b)
}
func (m *ListPricesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPricesResponse.Marshal(b, m, deterministic)
}
func (m *ListPricesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPricesResponse.Merge(m, src)
}
func (m *ListPricesResponse) XXX_Size() int {
	return xxx_messageInfo_ListPricesResponse.Size(m)
}
func (m *ListPricesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPricesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPricesResponse proto.InternalMessageInfo

func (m *ListPricesResponse) GetPrices() []*model.Price {
	if m != nil {
		return m.Prices
	}
	return nil
}

type CreatePriceRequest struct {
	Payload              *model.Price `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreatePriceRequest) Reset()         { *m = CreatePriceRequest{} }
func (m *CreatePriceRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePriceRequest) ProtoMessage()    {}
func (*CreatePriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{14}
}

func (m *CreatePriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePriceRequest.Unmarshal(m, b)
}
func (m *CreatePriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePriceRequest.Marshal(b, m, deterministic)
}
func (m *CreatePriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePriceRequest.Merge(m, src)
}
func (m *CreatePriceRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePriceRequest.Size(m)
}
func (m *CreatePriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePriceRequest proto.InternalMessageInfo

func (m *CreatePriceRequest) GetPayload() *model.Price {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ListPositionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPositionsRequest) Reset()         { *m = ListPositionsRequest{} }
func (m *ListPositionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPositionsRequest) ProtoMessage()    {}
func (*ListPositionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{15}
}

func (m *ListPositionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPositionsRequest.Unmarshal(m, b)
}
func (m *ListPositionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPositionsRequest.Marshal(b, m, deterministic)
}
func (m *ListPositionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPositionsRequest.Merge(m, src)
}
func (m *ListPositionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPositionsRequest.Size(m)
}
func (m *ListPositionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPositionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPositionsRequest proto.InternalMessageInfo

type ListPositionsResponse struct {
	Positions            []*model.Position `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListPositionsResponse) Reset()         { *m = ListPositionsResponse{} }
func (m *ListPositionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPositionsResponse) ProtoMessage()    {}
func (*ListPositionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{16}
}

func (m *ListPositionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPositionsResponse.Unmarshal(m, b)
}
func (m *ListPositionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPositionsResponse.Marshal(b, m, deterministic)
}
func (m *ListPositionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPositionsResponse.Merge(m, src)
}
func (m *ListPositionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPositionsResponse.Size(m)
}
func (m *ListPositionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPositionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPositionsResponse proto.InternalMessageInfo

func (m *ListPositionsResponse) GetPositions() []*model.Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

type CreatePositionRequest struct {
	Payload              *model.Position `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreatePositionRequest) Reset()         { *m = CreatePositionRequest{} }
func (m *CreatePositionRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePositionRequest) ProtoMessage()    {}
func (*CreatePositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{17}
}

func (m *CreatePositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePositionRequest.Unmarshal(m, b)
}
func (m *CreatePositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePositionRequest.Marshal(b, m, deterministic)
}
func (m *CreatePositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePositionRequest.Merge(m, src)
}
func (m *CreatePositionRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePositionRequest.Size(m)
}
func (m *CreatePositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePositionRequest proto.InternalMessageInfo

func (m *CreatePositionRequest) GetPayload() *model.Position {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ListEmployeesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEmployeesRequest) Reset()         { *m = ListEmployeesRequest{} }
func (m *ListEmployeesRequest) String() string { return proto.CompactTextString(m) }
func (*ListEmployeesRequest) ProtoMessage()    {}
func (*ListEmployeesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{18}
}

func (m *ListEmployeesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEmployeesRequest.Unmarshal(m, b)
}
func (m *ListEmployeesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEmployeesRequest.Marshal(b, m, deterministic)
}
func (m *ListEmployeesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEmployeesRequest.Merge(m, src)
}
func (m *ListEmployeesRequest) XXX_Size() int {
	return xxx_messageInfo_ListEmployeesRequest.Size(m)
}
func (m *ListEmployeesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEmployeesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEmployeesRequest proto.InternalMessageInfo

type ListEmployeesResponse struct {
	Employees            []*model.Employee `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListEmployeesResponse) Reset()         { *m = ListEmployeesResponse{} }
func (m *ListEmployeesResponse) String() string { return proto.CompactTextString(m) }
func (*ListEmployeesResponse) ProtoMessage()    {}
func (*ListEmployeesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{19}
}

func (m *ListEmployeesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEmployeesResponse.Unmarshal(m, b)
}
func (m *ListEmployeesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEmployeesResponse.Marshal(b, m, deterministic)
}
func (m *ListEmployeesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEmployeesResponse.Merge(m, src)
}
func (m *ListEmployeesResponse) XXX_Size() int {
	return xxx_messageInfo_ListEmployeesResponse.Size(m)
}
func (m *ListEmployeesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEmployeesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEmployeesResponse proto.InternalMessageInfo

func (m *ListEmployeesResponse) GetEmployees() []*model.Employee {
	if m != nil {
		return m.Employees
	}
	return nil
}

type CreateEmployeeRequest struct {
	Payload              *model.Employee `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateEmployeeRequest) Reset()         { *m = CreateEmployeeRequest{} }
func (m *CreateEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateEmployeeRequest) ProtoMessage()    {}
func (*CreateEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{20}
}

func (m *CreateEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateEmployeeRequest.Unmarshal(m, b)
}
func (m *CreateEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *CreateEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateEmployeeRequest.Merge(m, src)
}
func (m *CreateEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateEmployeeRequest.Size(m)
}
func (m *CreateEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateEmployeeRequest proto.InternalMessageInfo

func (m *CreateEmployeeRequest) GetPayload() *model.Employee {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ListMethodsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMethodsRequest) Reset()         { *m = ListMethodsRequest{} }
func (m *ListMethodsRequest) String() string { return proto.CompactTextString(m) }
func (*ListMethodsRequest) ProtoMessage()    {}
func (*ListMethodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{21}
}

func (m *ListMethodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMethodsRequest.Unmarshal(m, b)
}
func (m *ListMethodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMethodsRequest.Marshal(b, m, deterministic)
}
func (m *ListMethodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMethodsRequest.Merge(m, src)
}
func (m *ListMethodsRequest) XXX_Size() int {
	return xxx_messageInfo_ListMethodsRequest.Size(m)
}
func (m *ListMethodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMethodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMethodsRequest proto.InternalMessageInfo

type ListMethodsResponse struct {
	Methods              []*model.Method `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListMethodsResponse) Reset()         { *m = ListMethodsResponse{} }
func (m *ListMethodsResponse) String() string { return proto.CompactTextString(m) }
func (*ListMethodsResponse) ProtoMessage()    {}
func (*ListMethodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{22}
}

func (m *ListMethodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMethodsResponse.Unmarshal(m, b)
}
func (m *ListMethodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMethodsResponse.Marshal(b, m, deterministic)
}
func (m *ListMethodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMethodsResponse.Merge(m, src)
}
func (m *ListMethodsResponse) XXX_Size() int {
	return xxx_messageInfo_ListMethodsResponse.Size(m)
}
func (m *ListMethodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMethodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMethodsResponse proto.InternalMessageInfo

func (m *ListMethodsResponse) GetMethods() []*model.Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

type CreateMethodRequest struct {
	Payload              *model.Method `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateMethodRequest) Reset()         { *m = CreateMethodRequest{} }
func (m *CreateMethodRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMethodRequest) ProtoMessage()    {}
func (*CreateMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{23}
}

func (m *CreateMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMethodRequest.Unmarshal(m, b)
}
func (m *CreateMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMethodRequest.Marshal(b, m, deterministic)
}
func (m *CreateMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMethodRequest.Merge(m, src)
}
func (m *CreateMethodRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMethodRequest.Size(m)
}
func (m *CreateMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMethodRequest proto.InternalMessageInfo

func (m *CreateMethodRequest) GetPayload() *model.Method {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ListReceiptsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReceiptsRequest) Reset()         { *m = ListReceiptsRequest{} }
func (m *ListReceiptsRequest) String() string { return proto.CompactTextString(m) }
func (*ListReceiptsRequest) ProtoMessage()    {}
func (*ListReceiptsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{24}
}

func (m *ListReceiptsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReceiptsRequest.Unmarshal(m, b)
}
func (m *ListReceiptsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReceiptsRequest.Marshal(b, m, deterministic)
}
func (m *ListReceiptsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReceiptsRequest.Merge(m, src)
}
func (m *ListReceiptsRequest) XXX_Size() int {
	return xxx_messageInfo_ListReceiptsRequest.Size(m)
}
func (m *ListReceiptsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReceiptsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListReceiptsRequest proto.InternalMessageInfo

type ListReceiptsResponse struct {
	Receipts             []*model.Receipt `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListReceiptsResponse) Reset()         { *m = ListReceiptsResponse{} }
func (m *ListReceiptsResponse) String() string { return proto.CompactTextString(m) }
func (*ListReceiptsResponse) ProtoMessage()    {}
func (*ListReceiptsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{25}
}

func (m *ListReceiptsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReceiptsResponse.Unmarshal(m, b)
}
func (m *ListReceiptsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReceiptsResponse.Marshal(b, m, deterministic)
}
func (m *ListReceiptsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReceiptsResponse.Merge(m, src)
}
func (m *ListReceiptsResponse) XXX_Size() int {
	return xxx_messageInfo_ListReceiptsResponse.Size(m)
}
func (m *ListReceiptsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReceiptsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListReceiptsResponse proto.InternalMessageInfo

func (m *ListReceiptsResponse) GetReceipts() []*model.Receipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

type CreateReceiptRequest struct {
	Payload              *model.Receipt `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreateReceiptRequest) Reset()         { *m = CreateReceiptRequest{} }
func (m *CreateReceiptRequest) String() string { return proto.CompactTextString(m) }
func (*CreateReceiptRequest) ProtoMessage()    {}
func (*CreateReceiptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{26}
}

func (m *CreateReceiptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReceiptRequest.Unmarshal(m, b)
}
func (m *CreateReceiptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReceiptRequest.Marshal(b, m, deterministic)
}
func (m *CreateReceiptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReceiptRequest.Merge(m, src)
}
func (m *CreateReceiptRequest) XXX_Size() int {
	return xxx_messageInfo_CreateReceiptRequest.Size(m)
}
func (m *CreateReceiptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReceiptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReceiptRequest proto.InternalMessageInfo

func (m *CreateReceiptRequest) GetPayload() *model.Receipt {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ListPurchasesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPurchasesRequest) Reset()         { *m = ListPurchasesRequest{} }
func (m *ListPurchasesRequest) String() string { return proto.CompactTextString(m) }
func (*ListPurchasesRequest) ProtoMessage()    {}
func (*ListPurchasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{27}
}

func (m *ListPurchasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPurchasesRequest.Unmarshal(m, b)
}
func (m *ListPurchasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPurchasesRequest.Marshal(b, m, deterministic)
}
func (m *ListPurchasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPurchasesRequest.Merge(m, src)
}
func (m *ListPurchasesRequest) XXX_Size() int {
	return xxx_messageInfo_ListPurchasesRequest.Size(m)
}
func (m *ListPurchasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPurchasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPurchasesRequest proto.InternalMessageInfo

type ListPurchasesResponse struct {
	Purchases            []*model.Purchase `protobuf:"bytes,1,rep,name=purchases,proto3" json:"purchases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListPurchasesResponse) Reset()         { *m = ListPurchasesResponse{} }
func (m *ListPurchasesResponse) String() string { return proto.CompactTextString(m) }
func (*ListPurchasesResponse) ProtoMessage()    {}
func (*ListPurchasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{28}
}

func (m *ListPurchasesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPurchasesResponse.Unmarshal(m, b)
}
func (m *ListPurchasesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPurchasesResponse.Marshal(b, m, deterministic)
}
func (m *ListPurchasesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPurchasesResponse.Merge(m, src)
}
func (m *ListPurchasesResponse) XXX_Size() int {
	return xxx_messageInfo_ListPurchasesResponse.Size(m)
}
func (m *ListPurchasesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPurchasesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPurchasesResponse proto.InternalMessageInfo

func (m *ListPurchasesResponse) GetPurchases() []*model.Purchase {
	if m != nil {
		return m.Purchases
	}
	return nil
}

type CreatePurchaseRequest struct {
	Payload              *model.Purchase `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreatePurchaseRequest) Reset()         { *m = CreatePurchaseRequest{} }
func (m *CreatePurchaseRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePurchaseRequest) ProtoMessage()    {}
func (*CreatePurchaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_66a32e9888568cf7, []int{29}
}

func (m *CreatePurchaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePurchaseRequest.Unmarshal(m, b)
}
func (m *CreatePurchaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePurchaseRequest.Marshal(b, m, deterministic)
}
func (m *CreatePurchaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePurchaseRequest.Merge(m, src)
}
func (m *CreatePurchaseRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePurchaseRequest.Size(m)
}
func (m *CreatePurchaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePurchaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePurchaseRequest proto.InternalMessageInfo

func (m *CreatePurchaseRequest) GetPayload() *model.Purchase {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*ListCurrencyRequest)(nil), "writer.ListCurrencyRequest")
	proto.RegisterType((*ListCurrencyResponse)(nil), "writer.ListCurrencyResponse")
	proto.RegisterType((*CreateCurrencyRequest)(nil), "writer.CreateCurrencyRequest")
	proto.RegisterType((*ListRatesOfExchangeRequest)(nil), "writer.ListRatesOfExchangeRequest")
	proto.RegisterType((*ListRatesOfExchangeResponse)(nil), "writer.ListRatesOfExchangeResponse")
	proto.RegisterType((*CreateRateOfExchangeRequest)(nil), "writer.CreateRateOfExchangeRequest")
	proto.RegisterType((*ListLocationsRequest)(nil), "writer.ListLocationsRequest")
	proto.RegisterType((*ListLocationsResponse)(nil), "writer.ListLocationsResponse")
	proto.RegisterType((*CreateLocationRequest)(nil), "writer.CreateLocationRequest")
	proto.RegisterType((*ListProductsRequest)(nil), "writer.ListProductsRequest")
	proto.RegisterType((*ListProductsResponse)(nil), "writer.ListProductsResponse")
	proto.RegisterType((*CreateProductRequest)(nil), "writer.CreateProductRequest")
	proto.RegisterType((*ListPricesRequest)(nil), "writer.ListPricesRequest")
	proto.RegisterType((*ListPricesResponse)(nil), "writer.ListPricesResponse")
	proto.RegisterType((*CreatePriceRequest)(nil), "writer.CreatePriceRequest")
	proto.RegisterType((*ListPositionsRequest)(nil), "writer.ListPositionsRequest")
	proto.RegisterType((*ListPositionsResponse)(nil), "writer.ListPositionsResponse")
	proto.RegisterType((*CreatePositionRequest)(nil), "writer.CreatePositionRequest")
	proto.RegisterType((*ListEmployeesRequest)(nil), "writer.ListEmployeesRequest")
	proto.RegisterType((*ListEmployeesResponse)(nil), "writer.ListEmployeesResponse")
	proto.RegisterType((*CreateEmployeeRequest)(nil), "writer.CreateEmployeeRequest")
	proto.RegisterType((*ListMethodsRequest)(nil), "writer.ListMethodsRequest")
	proto.RegisterType((*ListMethodsResponse)(nil), "writer.ListMethodsResponse")
	proto.RegisterType((*CreateMethodRequest)(nil), "writer.CreateMethodRequest")
	proto.RegisterType((*ListReceiptsRequest)(nil), "writer.ListReceiptsRequest")
	proto.RegisterType((*ListReceiptsResponse)(nil), "writer.ListReceiptsResponse")
	proto.RegisterType((*CreateReceiptRequest)(nil), "writer.CreateReceiptRequest")
	proto.RegisterType((*ListPurchasesRequest)(nil), "writer.ListPurchasesRequest")
	proto.RegisterType((*ListPurchasesResponse)(nil), "writer.ListPurchasesResponse")
	proto.RegisterType((*CreatePurchaseRequest)(nil), "writer.CreatePurchaseRequest")
}

func init() {
	proto.RegisterFile("proto/svc-storage-writer/writer/svc-storage-writer.proto", fileDescriptor_66a32e9888568cf7)
}

var fileDescriptor_66a32e9888568cf7 = []byte{
	// 867 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x97, 0x6d, 0x4b, 0x1b, 0x4b,
	0x14, 0xc7, 0x57, 0x2e, 0xa8, 0x77, 0xe2, 0x03, 0x8e, 0xc9, 0xc5, 0x3b, 0x51, 0x90, 0xf1, 0x72,
	0xb5, 0x2d, 0x26, 0x60, 0x29, 0xb4, 0x45, 0xfa, 0xa0, 0x58, 0x0a, 0xb5, 0x56, 0xd6, 0x42, 0x5f,
	0xea, 0xba, 0x19, 0x93, 0x85, 0x24, 0xb3, 0x9d, 0xdd, 0xd8, 0xfa, 0x41, 0xfb, 0x7d, 0x4a, 0x32,
	0x67, 0x9e, 0xce, 0xae, 0xcd, 0x1b, 0xc5, 0xf3, 0x3f, 0x33, 0xfb, 0x9b, 0x39, 0x67, 0xce, 0x1f,
	0xc9, 0xcb, 0x5c, 0xc9, 0x52, 0x76, 0x8b, 0xfb, 0xf4, 0xb0, 0x28, 0xa5, 0x4a, 0xfa, 0xe2, 0xf0,
	0x87, 0xca, 0x4a, 0xa1, 0xba, 0xf0, 0xab, 0xaa, 0x74, 0x66, 0x4b, 0xe8, 0xa2, 0xfe, 0x8b, 0xbd,
	0xe8, 0x67, 0xe5, 0x60, 0x72, 0xdb, 0x49, 0xe5, 0xa8, 0x3b, 0x12, 0xe5, 0x40, 0x65, 0xc3, 0x4c,
	0x8e, 0xbb, 0x7d, 0x39, 0x51, 0x23, 0x51, 0x76, 0xf5, 0xfe, 0x23, 0xd9, 0x13, 0x43, 0xfd, 0x53,
	0x2f, 0xe7, 0x2d, 0xb2, 0x79, 0x9e, 0x15, 0xe5, 0xe9, 0x44, 0x29, 0x31, 0x4e, 0x1f, 0x62, 0xf1,
	0x7d, 0x22, 0x8a, 0x92, 0x9f, 0x92, 0x66, 0x18, 0x2e, 0x72, 0x39, 0x2e, 0x04, 0x7d, 0x46, 0x96,
	0x53, 0x88, 0x6d, 0x2d, 0xec, 0xfe, 0x75, 0xd0, 0x38, 0x5a, 0xef, 0xe8, 0xed, 0x6c, 0xaa, 0x4d,
	0xe0, 0x27, 0xa4, 0x75, 0xaa, 0x44, 0x52, 0x0a, 0xb4, 0x3b, 0x7d, 0x42, 0x96, 0xf2, 0xe4, 0x61,
	0x28, 0x93, 0xde, 0xd6, 0xc2, 0xee, 0x42, 0xdd, 0x26, 0x46, 0xe7, 0xdb, 0x84, 0x4d, 0x41, 0xe2,
	0xa4, 0x14, 0xc5, 0x97, 0xbb, 0xb3, 0x9f, 0xe9, 0x20, 0x19, 0xf7, 0x85, 0xc1, 0xbc, 0x21, 0xed,
	0x5a, 0x15, 0x68, 0xdf, 0x93, 0x0d, 0x35, 0x95, 0xae, 0xe5, 0xdd, 0xb5, 0x00, 0x11, 0xb0, 0x5b,
	0xf0, 0xc5, 0xe9, 0x52, 0x6f, 0xe5, 0xba, 0x0a, 0xb7, 0xe2, 0x17, 0xa4, 0xad, 0xcf, 0x80, 0x12,
	0xe1, 0x24, 0x5d, 0x7c, 0x92, 0x47, 0xf6, 0xb5, 0xe7, 0xf9, 0x47, 0x5f, 0xec, 0xb9, 0x4c, 0x93,
	0x32, 0x93, 0xe3, 0xc2, 0x9c, 0xe4, 0x03, 0x69, 0xa1, 0x38, 0x9c, 0xe1, 0x90, 0xfc, 0x3d, 0x34,
	0x41, 0x74, 0xe5, 0x26, 0x39, 0x76, 0x19, 0xee, 0xce, 0xad, 0x38, 0xef, 0xce, 0x6d, 0xa2, 0x65,
	0x84, 0x9e, 0xb8, 0x54, 0xb2, 0x37, 0x49, 0x4b, 0x8b, 0x78, 0xa2, 0xd1, 0x5d, 0x18, 0x08, 0x9f,
	0x92, 0xe5, 0x1c, 0x62, 0x00, 0xb8, 0x06, 0x5b, 0x43, 0x6a, 0x6c, 0x75, 0xfe, 0x8e, 0x34, 0x35,
	0x9e, 0x91, 0x80, 0xee, 0x00, 0xd3, 0xe1, 0x2d, 0x2c, 0xdc, 0x26, 0xd9, 0xd0, 0x14, 0x59, 0x2a,
	0x2c, 0xda, 0x6b, 0x42, 0xfd, 0x20, 0x80, 0xfd, 0x47, 0x16, 0xf3, 0x59, 0x04, 0xb0, 0x56, 0xec,
	0x9e, 0x59, 0x2a, 0x62, 0xd0, 0xf8, 0x31, 0xa1, 0x06, 0x69, 0x1a, 0x06, 0xa0, 0xff, 0x31, 0x50,
	0xb8, 0x18, 0xd7, 0xf3, 0x52, 0x16, 0x59, 0x5d, 0x3d, 0xbd, 0xb8, 0xab, 0x67, 0x6e, 0x82, 0xa8,
	0x9e, 0x26, 0x39, 0x76, 0x19, 0xae, 0x9e, 0x56, 0x9c, 0x57, 0x4f, 0x9b, 0x88, 0x19, 0xcf, 0x46,
	0xf9, 0x50, 0x3e, 0x08, 0x81, 0x19, 0xbd, 0xb8, 0x63, 0x14, 0x26, 0x88, 0x18, 0x4d, 0x72, 0xec,
	0x32, 0x1c, 0xa3, 0x15, 0xe7, 0x31, 0xda, 0x44, 0xcb, 0xd8, 0xd4, 0x15, 0xfc, 0x2c, 0xca, 0x81,
	0xec, 0x59, 0xc2, 0x37, 0xba, 0x13, 0x6d, 0x14, 0xf8, 0xf6, 0xc9, 0xd2, 0x48, 0x87, 0x80, 0x6e,
	0x15, 0xf6, 0xd5, 0x89, 0xb1, 0x51, 0xa7, 0xeb, 0x35, 0x19, 0x08, 0xc0, 0xb5, 0x8f, 0xb9, 0xf0,
	0x7a, 0xf4, 0x12, 0x62, 0x91, 0x8a, 0x2c, 0xaf, 0xbc, 0x04, 0x17, 0x76, 0x2f, 0x41, 0x41, 0x0c,
	0xbd, 0x04, 0x48, 0x8d, 0xad, 0xee, 0x5e, 0x82, 0x91, 0xe6, 0xbd, 0x04, 0x93, 0x57, 0x69, 0xbd,
	0x89, 0x4a, 0x07, 0x49, 0x51, 0x29, 0xab, 0x17, 0xf7, 0x5a, 0xcf, 0x04, 0x71, 0xeb, 0x41, 0x3c,
	0x76, 0x19, 0x5e, 0xeb, 0x19, 0x71, 0x6e, 0xeb, 0x99, 0x44, 0xa3, 0x1f, 0xfd, 0x6a, 0x90, 0xe6,
	0x95, 0xb6, 0xad, 0x6f, 0x33, 0x9f, 0xba, 0x12, 0xea, 0x3e, 0x4b, 0x05, 0xfd, 0x44, 0x56, 0x7c,
	0x83, 0xa1, 0xed, 0x0e, 0xb8, 0x5a, 0x8d, 0x1b, 0xb1, 0xed, 0x7a, 0x51, 0x1f, 0x8b, 0x47, 0xf4,
	0x84, 0xac, 0x85, 0x46, 0x43, 0x77, 0xcc, 0x8a, 0x5a, 0x03, 0x62, 0xd8, 0x6f, 0x78, 0x44, 0x6f,
	0xa0, 0xd4, 0xe1, 0xfc, 0xa7, 0xdc, 0xff, 0x74, 0xbd, 0x0b, 0xb1, 0xbd, 0x3f, 0xe6, 0x58, 0xca,
	0xaf, 0xb6, 0xe2, 0x81, 0x37, 0xd0, 0xbd, 0x90, 0xb5, 0xd6, 0x68, 0x58, 0xbd, 0xaf, 0xf0, 0x88,
	0x5e, 0x90, 0xd5, 0xc0, 0x38, 0x68, 0x70, 0x59, 0xd8, 0x67, 0xd8, 0xce, 0x23, 0x6a, 0xf5, 0x2e,
	0x8d, 0x88, 0xef, 0x12, 0x19, 0x0b, 0xc3, 0x3e, 0xc2, 0x23, 0x53, 0x5c, 0xe3, 0x14, 0x61, 0x71,
	0x91, 0xad, 0x84, 0xc5, 0xc5, 0xe6, 0xc2, 0x23, 0xfa, 0x96, 0xac, 0x06, 0x96, 0xe1, 0x0e, 0x58,
	0xe7, 0x24, 0x0c, 0x19, 0x07, 0x8f, 0xe8, 0x19, 0x21, 0xce, 0x1c, 0xe8, 0xbf, 0xe1, 0xe7, 0x3c,
	0x17, 0x61, 0xac, 0x4e, 0xb2, 0x1c, 0xaf, 0x48, 0xc3, 0xf3, 0x09, 0xca, 0x30, 0x85, 0x33, 0x0f,
	0x16, 0x78, 0x85, 0xab, 0x91, 0x35, 0x83, 0xb0, 0x46, 0xd8, 0x3b, 0xc2, 0x1a, 0x55, 0x1c, 0xc4,
	0xaf, 0x91, 0x11, 0x71, 0x8d, 0x90, 0x59, 0x30, 0xec, 0x0d, 0x8e, 0xc9, 0x0e, 0xff, 0x90, 0x09,
	0x7b, 0x45, 0xc8, 0x54, 0x71, 0x0c, 0x9f, 0xc9, 0x88, 0x98, 0x09, 0x99, 0x03, 0xc3, 0x5e, 0xc0,
	0x23, 0xfa, 0x91, 0x34, 0xbc, 0x71, 0x4f, 0x83, 0x7a, 0x84, 0xce, 0xc0, 0xda, 0xb5, 0x9a, 0xa5,
	0x39, 0x26, 0x2b, 0xfe, 0xe0, 0x77, 0x1d, 0x58, 0x63, 0x07, 0x2c, 0x9c, 0xfe, 0xae, 0x7f, 0xcd,
	0x7c, 0x0f, 0xfb, 0x17, 0x99, 0x41, 0xd8, 0xbf, 0xd8, 0x12, 0xfc, 0xfe, 0x05, 0x0d, 0xf7, 0x6f,
	0x38, 0xff, 0x19, 0x1a, 0xf7, 0x5e, 0xf7, 0x98, 0xc1, 0x8c, 0xba, 0x07, 0x8d, 0x7f, 0xd4, 0x3d,
	0xd8, 0x04, 0x82, 0xee, 0x01, 0xb1, 0xd2, 0x3d, 0xe1, 0xbc, 0x67, 0x78, 0xbc, 0xf3, 0xe8, 0x76,
	0x71, 0xf6, 0xdf, 0xc3, 0xf3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x09, 0x27, 0xb3, 0x84, 0xb8,
	0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageWriterServiceClient is the client API for StorageWriterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageWriterServiceClient interface {
	ListCurrency(ctx context.Context, in *ListCurrencyRequest, opts ...grpc.CallOption) (*ListCurrencyResponse, error)
	CreateCurrency(ctx context.Context, in *CreateCurrencyRequest, opts ...grpc.CallOption) (*model.Currency, error)
	ListRatesOfExchange(ctx context.Context, in *ListRatesOfExchangeRequest, opts ...grpc.CallOption) (*ListRatesOfExchangeResponse, error)
	CreateRateOfExchange(ctx context.Context, in *CreateRateOfExchangeRequest, opts ...grpc.CallOption) (*model.RateOfExchange, error)
	ListLocations(ctx context.Context, in *ListLocationsRequest, opts ...grpc.CallOption) (*ListLocationsResponse, error)
	CreateLocation(ctx context.Context, in *CreateLocationRequest, opts ...grpc.CallOption) (*model.Location, error)
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*model.Product, error)
	ListPrices(ctx context.Context, in *ListPricesRequest, opts ...grpc.CallOption) (*ListPricesResponse, error)
	CreatePrice(ctx context.Context, in *CreatePriceRequest, opts ...grpc.CallOption) (*model.Price, error)
	ListPositions(ctx context.Context, in *ListPositionsRequest, opts ...grpc.CallOption) (*ListPositionsResponse, error)
	CreatePosition(ctx context.Context, in *CreatePositionRequest, opts ...grpc.CallOption) (*model.Position, error)
	ListEmployees(ctx context.Context, in *ListEmployeesRequest, opts ...grpc.CallOption) (*ListEmployeesResponse, error)
	CreateEmployee(ctx context.Context, in *CreateEmployeeRequest, opts ...grpc.CallOption) (*model.Employee, error)
	ListMethods(ctx context.Context, in *ListMethodsRequest, opts ...grpc.CallOption) (*ListMethodsResponse, error)
	CreateMethod(ctx context.Context, in *CreateMethodRequest, opts ...grpc.CallOption) (*model.Method, error)
	ListReceipts(ctx context.Context, in *ListReceiptsRequest, opts ...grpc.CallOption) (*ListReceiptsResponse, error)
	CreateReceipt(ctx context.Context, in *CreateReceiptRequest, opts ...grpc.CallOption) (*model.Receipt, error)
	ListPurchases(ctx context.Context, in *ListPurchasesRequest, opts ...grpc.CallOption) (*ListPurchasesResponse, error)
	CreatePurchase(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*model.Purchase, error)
}

type storageWriterServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorageWriterServiceClient(cc *grpc.ClientConn) StorageWriterServiceClient {
	return &storageWriterServiceClient{cc}
}

func (c *storageWriterServiceClient) ListCurrency(ctx context.Context, in *ListCurrencyRequest, opts ...grpc.CallOption) (*ListCurrencyResponse, error) {
	out := new(ListCurrencyResponse)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/ListCurrency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) CreateCurrency(ctx context.Context, in *CreateCurrencyRequest, opts ...grpc.CallOption) (*model.Currency, error) {
	out := new(model.Currency)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/CreateCurrency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) ListRatesOfExchange(ctx context.Context, in *ListRatesOfExchangeRequest, opts ...grpc.CallOption) (*ListRatesOfExchangeResponse, error) {
	out := new(ListRatesOfExchangeResponse)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/ListRatesOfExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) CreateRateOfExchange(ctx context.Context, in *CreateRateOfExchangeRequest, opts ...grpc.CallOption) (*model.RateOfExchange, error) {
	out := new(model.RateOfExchange)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/CreateRateOfExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) ListLocations(ctx context.Context, in *ListLocationsRequest, opts ...grpc.CallOption) (*ListLocationsResponse, error) {
	out := new(ListLocationsResponse)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/ListLocations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) CreateLocation(ctx context.Context, in *CreateLocationRequest, opts ...grpc.CallOption) (*model.Location, error) {
	out := new(model.Location)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/CreateLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/ListProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*model.Product, error) {
	out := new(model.Product)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/CreateProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) ListPrices(ctx context.Context, in *ListPricesRequest, opts ...grpc.CallOption) (*ListPricesResponse, error) {
	out := new(ListPricesResponse)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/ListPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) CreatePrice(ctx context.Context, in *CreatePriceRequest, opts ...grpc.CallOption) (*model.Price, error) {
	out := new(model.Price)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/CreatePrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) ListPositions(ctx context.Context, in *ListPositionsRequest, opts ...grpc.CallOption) (*ListPositionsResponse, error) {
	out := new(ListPositionsResponse)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/ListPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) CreatePosition(ctx context.Context, in *CreatePositionRequest, opts ...grpc.CallOption) (*model.Position, error) {
	out := new(model.Position)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/CreatePosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) ListEmployees(ctx context.Context, in *ListEmployeesRequest, opts ...grpc.CallOption) (*ListEmployeesResponse, error) {
	out := new(ListEmployeesResponse)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/ListEmployees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) CreateEmployee(ctx context.Context, in *CreateEmployeeRequest, opts ...grpc.CallOption) (*model.Employee, error) {
	out := new(model.Employee)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/CreateEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) ListMethods(ctx context.Context, in *ListMethodsRequest, opts ...grpc.CallOption) (*ListMethodsResponse, error) {
	out := new(ListMethodsResponse)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/ListMethods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) CreateMethod(ctx context.Context, in *CreateMethodRequest, opts ...grpc.CallOption) (*model.Method, error) {
	out := new(model.Method)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/CreateMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) ListReceipts(ctx context.Context, in *ListReceiptsRequest, opts ...grpc.CallOption) (*ListReceiptsResponse, error) {
	out := new(ListReceiptsResponse)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/ListReceipts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) CreateReceipt(ctx context.Context, in *CreateReceiptRequest, opts ...grpc.CallOption) (*model.Receipt, error) {
	out := new(model.Receipt)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/CreateReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) ListPurchases(ctx context.Context, in *ListPurchasesRequest, opts ...grpc.CallOption) (*ListPurchasesResponse, error) {
	out := new(ListPurchasesResponse)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/ListPurchases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriterServiceClient) CreatePurchase(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*model.Purchase, error) {
	out := new(model.Purchase)
	err := c.cc.Invoke(ctx, "/writer.StorageWriterService/CreatePurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageWriterServiceServer is the server API for StorageWriterService service.
type StorageWriterServiceServer interface {
	ListCurrency(context.Context, *ListCurrencyRequest) (*ListCurrencyResponse, error)
	CreateCurrency(context.Context, *CreateCurrencyRequest) (*model.Currency, error)
	ListRatesOfExchange(context.Context, *ListRatesOfExchangeRequest) (*ListRatesOfExchangeResponse, error)
	CreateRateOfExchange(context.Context, *CreateRateOfExchangeRequest) (*model.RateOfExchange, error)
	ListLocations(context.Context, *ListLocationsRequest) (*ListLocationsResponse, error)
	CreateLocation(context.Context, *CreateLocationRequest) (*model.Location, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	CreateProduct(context.Context, *CreateProductRequest) (*model.Product, error)
	ListPrices(context.Context, *ListPricesRequest) (*ListPricesResponse, error)
	CreatePrice(context.Context, *CreatePriceRequest) (*model.Price, error)
	ListPositions(context.Context, *ListPositionsRequest) (*ListPositionsResponse, error)
	CreatePosition(context.Context, *CreatePositionRequest) (*model.Position, error)
	ListEmployees(context.Context, *ListEmployeesRequest) (*ListEmployeesResponse, error)
	CreateEmployee(context.Context, *CreateEmployeeRequest) (*model.Employee, error)
	ListMethods(context.Context, *ListMethodsRequest) (*ListMethodsResponse, error)
	CreateMethod(context.Context, *CreateMethodRequest) (*model.Method, error)
	ListReceipts(context.Context, *ListReceiptsRequest) (*ListReceiptsResponse, error)
	CreateReceipt(context.Context, *CreateReceiptRequest) (*model.Receipt, error)
	ListPurchases(context.Context, *ListPurchasesRequest) (*ListPurchasesResponse, error)
	CreatePurchase(context.Context, *CreatePurchaseRequest) (*model.Purchase, error)
}

// UnimplementedStorageWriterServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStorageWriterServiceServer struct {
}

func (*UnimplementedStorageWriterServiceServer) ListCurrency(ctx context.Context, req *ListCurrencyRequest) (*ListCurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCurrency not implemented")
}
func (*UnimplementedStorageWriterServiceServer) CreateCurrency(ctx context.Context, req *CreateCurrencyRequest) (*model.Currency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCurrency not implemented")
}
func (*UnimplementedStorageWriterServiceServer) ListRatesOfExchange(ctx context.Context, req *ListRatesOfExchangeRequest) (*ListRatesOfExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRatesOfExchange not implemented")
}
func (*UnimplementedStorageWriterServiceServer) CreateRateOfExchange(ctx context.Context, req *CreateRateOfExchangeRequest) (*model.RateOfExchange, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRateOfExchange not implemented")
}
func (*UnimplementedStorageWriterServiceServer) ListLocations(ctx context.Context, req *ListLocationsRequest) (*ListLocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLocations not implemented")
}
func (*UnimplementedStorageWriterServiceServer) CreateLocation(ctx context.Context, req *CreateLocationRequest) (*model.Location, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLocation not implemented")
}
func (*UnimplementedStorageWriterServiceServer) ListProducts(ctx context.Context, req *ListProductsRequest) (*ListProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (*UnimplementedStorageWriterServiceServer) CreateProduct(ctx context.Context, req *CreateProductRequest) (*model.Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProduct not implemented")
}
func (*UnimplementedStorageWriterServiceServer) ListPrices(ctx context.Context, req *ListPricesRequest) (*ListPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPrices not implemented")
}
func (*UnimplementedStorageWriterServiceServer) CreatePrice(ctx context.Context, req *CreatePriceRequest) (*model.Price, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePrice not implemented")
}
func (*UnimplementedStorageWriterServiceServer) ListPositions(ctx context.Context, req *ListPositionsRequest) (*ListPositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPositions not implemented")
}
func (*UnimplementedStorageWriterServiceServer) CreatePosition(ctx context.Context, req *CreatePositionRequest) (*model.Position, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePosition not implemented")
}
func (*UnimplementedStorageWriterServiceServer) ListEmployees(ctx context.Context, req *ListEmployeesRequest) (*ListEmployeesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEmployees not implemented")
}
func (*UnimplementedStorageWriterServiceServer) CreateEmployee(ctx context.Context, req *CreateEmployeeRequest) (*model.Employee, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEmployee not implemented")
}
func (*UnimplementedStorageWriterServiceServer) ListMethods(ctx context.Context, req *ListMethodsRequest) (*ListMethodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMethods not implemented")
}
func (*UnimplementedStorageWriterServiceServer) CreateMethod(ctx context.Context, req *CreateMethodRequest) (*model.Method, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMethod not implemented")
}
func (*UnimplementedStorageWriterServiceServer) ListReceipts(ctx context.Context, req *ListReceiptsRequest) (*ListReceiptsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReceipts not implemented")
}
func (*UnimplementedStorageWriterServiceServer) CreateReceipt(ctx context.Context, req *CreateReceiptRequest) (*model.Receipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateReceipt not implemented")
}
func (*UnimplementedStorageWriterServiceServer) ListPurchases(ctx context.Context, req *ListPurchasesRequest) (*ListPurchasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPurchases not implemented")
}
func (*UnimplementedStorageWriterServiceServer) CreatePurchase(ctx context.Context, req *CreatePurchaseRequest) (*model.Purchase, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePurchase not implemented")
}

func RegisterStorageWriterServiceServer(s *grpc.Server, srv StorageWriterServiceServer) {
	s.RegisterService(&_StorageWriterService_serviceDesc, srv)
}

func _StorageWriterService_ListCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).ListCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/ListCurrency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).ListCurrency(ctx, req.(*ListCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_CreateCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).CreateCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/CreateCurrency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).CreateCurrency(ctx, req.(*CreateCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_ListRatesOfExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRatesOfExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).ListRatesOfExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/ListRatesOfExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).ListRatesOfExchange(ctx, req.(*ListRatesOfExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_CreateRateOfExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRateOfExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).CreateRateOfExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/CreateRateOfExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).CreateRateOfExchange(ctx, req.(*CreateRateOfExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_ListLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).ListLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/ListLocations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).ListLocations(ctx, req.(*ListLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_CreateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).CreateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/CreateLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).CreateLocation(ctx, req.(*CreateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/ListProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_ListPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).ListPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/ListPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).ListPrices(ctx, req.(*ListPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_CreatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).CreatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/CreatePrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).CreatePrice(ctx, req.(*CreatePriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_ListPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).ListPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/ListPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).ListPositions(ctx, req.(*ListPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_CreatePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).CreatePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/CreatePosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).CreatePosition(ctx, req.(*CreatePositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_ListEmployees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEmployeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).ListEmployees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/ListEmployees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).ListEmployees(ctx, req.(*ListEmployeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_CreateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).CreateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/CreateEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).CreateEmployee(ctx, req.(*CreateEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_ListMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).ListMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/ListMethods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).ListMethods(ctx, req.(*ListMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_CreateMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).CreateMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/CreateMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).CreateMethod(ctx, req.(*CreateMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_ListReceipts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReceiptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).ListReceipts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/ListReceipts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).ListReceipts(ctx, req.(*ListReceiptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_CreateReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).CreateReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/CreateReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).CreateReceipt(ctx, req.(*CreateReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_ListPurchases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPurchasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).ListPurchases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/ListPurchases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).ListPurchases(ctx, req.(*ListPurchasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWriterService_CreatePurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriterServiceServer).CreatePurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/writer.StorageWriterService/CreatePurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriterServiceServer).CreatePurchase(ctx, req.(*CreatePurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageWriterService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "writer.StorageWriterService",
	HandlerType: (*StorageWriterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCurrency",
			Handler:    _StorageWriterService_ListCurrency_Handler,
		},
		{
			MethodName: "CreateCurrency",
			Handler:    _StorageWriterService_CreateCurrency_Handler,
		},
		{
			MethodName: "ListRatesOfExchange",
			Handler:    _StorageWriterService_ListRatesOfExchange_Handler,
		},
		{
			MethodName: "CreateRateOfExchange",
			Handler:    _StorageWriterService_CreateRateOfExchange_Handler,
		},
		{
			MethodName: "ListLocations",
			Handler:    _StorageWriterService_ListLocations_Handler,
		},
		{
			MethodName: "CreateLocation",
			Handler:    _StorageWriterService_CreateLocation_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _StorageWriterService_ListProducts_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _StorageWriterService_CreateProduct_Handler,
		},
		{
			MethodName: "ListPrices",
			Handler:    _StorageWriterService_ListPrices_Handler,
		},
		{
			MethodName: "CreatePrice",
			Handler:    _StorageWriterService_CreatePrice_Handler,
		},
		{
			MethodName: "ListPositions",
			Handler:    _StorageWriterService_ListPositions_Handler,
		},
		{
			MethodName: "CreatePosition",
			Handler:    _StorageWriterService_CreatePosition_Handler,
		},
		{
			MethodName: "ListEmployees",
			Handler:    _StorageWriterService_ListEmployees_Handler,
		},
		{
			MethodName: "CreateEmployee",
			Handler:    _StorageWriterService_CreateEmployee_Handler,
		},
		{
			MethodName: "ListMethods",
			Handler:    _StorageWriterService_ListMethods_Handler,
		},
		{
			MethodName: "CreateMethod",
			Handler:    _StorageWriterService_CreateMethod_Handler,
		},
		{
			MethodName: "ListReceipts",
			Handler:    _StorageWriterService_ListReceipts_Handler,
		},
		{
			MethodName: "CreateReceipt",
			Handler:    _StorageWriterService_CreateReceipt_Handler,
		},
		{
			MethodName: "ListPurchases",
			Handler:    _StorageWriterService_ListPurchases_Handler,
		},
		{
			MethodName: "CreatePurchase",
			Handler:    _StorageWriterService_CreatePurchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/svc-storage-writer/writer/svc-storage-writer.proto",
}
