// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/model/model.proto

package model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Currency struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Currency) Reset()         { *m = Currency{} }
func (m *Currency) String() string { return proto.CompactTextString(m) }
func (*Currency) ProtoMessage()    {}
func (*Currency) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{0}
}

func (m *Currency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Currency.Unmarshal(m, b)
}
func (m *Currency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Currency.Marshal(b, m, deterministic)
}
func (m *Currency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Currency.Merge(m, src)
}
func (m *Currency) XXX_Size() int {
	return xxx_messageInfo_Currency.Size(m)
}
func (m *Currency) XXX_DiscardUnknown() {
	xxx_messageInfo_Currency.DiscardUnknown(m)
}

var xxx_messageInfo_Currency proto.InternalMessageInfo

func (m *Currency) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Currency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Currency) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type RateOfExchange struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromId               uint32   `protobuf:"varint,2,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId                 uint32   `protobuf:"varint,3,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RateOfExchange) Reset()         { *m = RateOfExchange{} }
func (m *RateOfExchange) String() string { return proto.CompactTextString(m) }
func (*RateOfExchange) ProtoMessage()    {}
func (*RateOfExchange) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{1}
}

func (m *RateOfExchange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RateOfExchange.Unmarshal(m, b)
}
func (m *RateOfExchange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RateOfExchange.Marshal(b, m, deterministic)
}
func (m *RateOfExchange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RateOfExchange.Merge(m, src)
}
func (m *RateOfExchange) XXX_Size() int {
	return xxx_messageInfo_RateOfExchange.Size(m)
}
func (m *RateOfExchange) XXX_DiscardUnknown() {
	xxx_messageInfo_RateOfExchange.DiscardUnknown(m)
}

var xxx_messageInfo_RateOfExchange proto.InternalMessageInfo

func (m *RateOfExchange) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RateOfExchange) GetFromId() uint32 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *RateOfExchange) GetToId() uint32 {
	if m != nil {
		return m.ToId
	}
	return 0
}

func (m *RateOfExchange) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Location struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CurrencyId           uint32   `protobuf:"varint,4,opt,name=currency_id,json=currencyId,proto3" json:"currency_id,omitempty"`
	Status               bool     `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{2}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Location) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Location) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Location) GetCurrencyId() uint32 {
	if m != nil {
		return m.CurrencyId
	}
	return 0
}

func (m *Location) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type Product struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{3}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Price struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            uint32   `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	LocationId           uint32   `protobuf:"varint,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{4}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Price) GetProductId() uint32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

func (m *Price) GetLocationId() uint32 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *Price) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Position struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{5}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Position) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Position) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Employee struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PositionId           uint32   `protobuf:"varint,4,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
	LocationId           uint32   `protobuf:"varint,5,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{6}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Employee) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Employee) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Employee) GetPositionId() uint32 {
	if m != nil {
		return m.PositionId
	}
	return 0
}

func (m *Employee) GetLocationId() uint32 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

type Method struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method) Reset()         { *m = Method{} }
func (m *Method) String() string { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()    {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{7}
}

func (m *Method) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method.Unmarshal(m, b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method.Marshal(b, m, deterministic)
}
func (m *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(m, src)
}
func (m *Method) XXX_Size() int {
	return xxx_messageInfo_Method.Size(m)
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Method) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// TODO: change datetime type
type Receipt struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EmployeeId           uint32   `protobuf:"varint,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	LocationId           uint32   `protobuf:"varint,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	MethodId             uint32   `protobuf:"varint,4,opt,name=method_id,json=methodId,proto3" json:"method_id,omitempty"`
	Datetime             string   `protobuf:"bytes,5,opt,name=datetime,proto3" json:"datetime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{8}
}

func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Receipt) GetEmployeeId() uint32 {
	if m != nil {
		return m.EmployeeId
	}
	return 0
}

func (m *Receipt) GetLocationId() uint32 {
	if m != nil {
		return m.LocationId
	}
	return 0
}

func (m *Receipt) GetMethodId() uint32 {
	if m != nil {
		return m.MethodId
	}
	return 0
}

func (m *Receipt) GetDatetime() string {
	if m != nil {
		return m.Datetime
	}
	return ""
}

type Purchase struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ReceiptId            uint32   `protobuf:"varint,2,opt,name=receipt_id,json=receiptId,proto3" json:"receipt_id,omitempty"`
	PriceId              uint32   `protobuf:"varint,3,opt,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
	Amount               float32  `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Price                float32  `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Result               float32  `protobuf:"fixed32,6,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Purchase) Reset()         { *m = Purchase{} }
func (m *Purchase) String() string { return proto.CompactTextString(m) }
func (*Purchase) ProtoMessage()    {}
func (*Purchase) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d95f8c3a6adfa7f, []int{9}
}

func (m *Purchase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Purchase.Unmarshal(m, b)
}
func (m *Purchase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Purchase.Marshal(b, m, deterministic)
}
func (m *Purchase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Purchase.Merge(m, src)
}
func (m *Purchase) XXX_Size() int {
	return xxx_messageInfo_Purchase.Size(m)
}
func (m *Purchase) XXX_DiscardUnknown() {
	xxx_messageInfo_Purchase.DiscardUnknown(m)
}

var xxx_messageInfo_Purchase proto.InternalMessageInfo

func (m *Purchase) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Purchase) GetReceiptId() uint32 {
	if m != nil {
		return m.ReceiptId
	}
	return 0
}

func (m *Purchase) GetPriceId() uint32 {
	if m != nil {
		return m.PriceId
	}
	return 0
}

func (m *Purchase) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Purchase) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Purchase) GetResult() float32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Currency)(nil), "model.Currency")
	proto.RegisterType((*RateOfExchange)(nil), "model.RateOfExchange")
	proto.RegisterType((*Location)(nil), "model.Location")
	proto.RegisterType((*Product)(nil), "model.Product")
	proto.RegisterType((*Price)(nil), "model.Price")
	proto.RegisterType((*Position)(nil), "model.Position")
	proto.RegisterType((*Employee)(nil), "model.Employee")
	proto.RegisterType((*Method)(nil), "model.Method")
	proto.RegisterType((*Receipt)(nil), "model.Receipt")
	proto.RegisterType((*Purchase)(nil), "model.Purchase")
}

func init() { proto.RegisterFile("proto/model/model.proto", fileDescriptor_5d95f8c3a6adfa7f) }

var fileDescriptor_5d95f8c3a6adfa7f = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0xe5, 0x6e, 0x93, 0x3a, 0x53, 0xed, 0x1e, 0x0c, 0x62, 0x03, 0x2b, 0xd4, 0xc8, 0xa7,
	0x1e, 0x10, 0x1c, 0x78, 0x03, 0xd0, 0x1e, 0x22, 0x01, 0x1b, 0xe5, 0x05, 0x56, 0xc6, 0x76, 0xa9,
	0xa5, 0x24, 0x8e, 0x1c, 0x47, 0x62, 0x1f, 0x81, 0x3b, 0x07, 0xc4, 0xd3, 0x22, 0xff, 0x09, 0x89,
	0xe8, 0x22, 0xf5, 0xb0, 0x97, 0xca, 0xf3, 0xb3, 0x3b, 0xfd, 0xbe, 0x6f, 0x46, 0x85, 0xeb, 0xde,
	0x68, 0xab, 0xdf, 0xb5, 0x5a, 0xc8, 0x26, 0x7c, 0xbe, 0xf5, 0x84, 0x24, 0xbe, 0xa0, 0x1f, 0x00,
	0x7f, 0x1c, 0x8d, 0x91, 0x1d, 0x7f, 0x20, 0x57, 0xb0, 0x52, 0x22, 0x47, 0x05, 0xda, 0x5f, 0xd6,
	0x2b, 0x25, 0x08, 0x81, 0x75, 0xc7, 0x5a, 0x99, 0xaf, 0x0a, 0xb4, 0xcf, 0x6a, 0x7f, 0x76, 0x8c,
	0x6b, 0x21, 0xf3, 0x8b, 0xc0, 0xdc, 0x99, 0x0a, 0xb8, 0xaa, 0x99, 0x95, 0x77, 0x87, 0xdb, 0xef,
	0xfc, 0xc8, 0xba, 0x6f, 0xf2, 0xa4, 0xd3, 0x35, 0x6c, 0x0e, 0x46, 0xb7, 0xf7, 0x4a, 0xf8, 0x66,
	0x97, 0x75, 0xea, 0xca, 0x52, 0x90, 0x67, 0x90, 0x58, 0xed, 0xf0, 0x85, 0xc7, 0x6b, 0xab, 0x4b,
	0x41, 0x9e, 0x43, 0xd2, 0x1b, 0xc5, 0x65, 0xbe, 0x2e, 0xd0, 0x7e, 0x55, 0x87, 0x82, 0xfe, 0x40,
	0x80, 0x3f, 0x69, 0xce, 0xac, 0xd2, 0xdd, 0x59, 0x52, 0x0b, 0xd8, 0x0a, 0x39, 0x70, 0xa3, 0x7a,
	0xf7, 0x95, 0xa8, 0x78, 0x89, 0xc8, 0x0e, 0xb6, 0x3c, 0x9a, 0x77, 0x1a, 0xd6, 0xbe, 0x1d, 0x4c,
	0xa8, 0x14, 0xe4, 0x05, 0xa4, 0x83, 0x65, 0x76, 0x1c, 0xf2, 0xa4, 0x40, 0x7b, 0x5c, 0xc7, 0x8a,
	0xde, 0xc1, 0xa6, 0x32, 0x5a, 0x8c, 0xdc, 0x3e, 0x8d, 0x12, 0xda, 0x42, 0x52, 0x39, 0x97, 0x27,
	0xed, 0x5e, 0x03, 0xf4, 0xe1, 0x97, 0xe6, 0xf0, 0xb2, 0x48, 0x4a, 0xe1, 0x1c, 0x34, 0x31, 0x93,
	0x39, 0x45, 0x98, 0xd0, 0x7f, 0xb3, 0xac, 0x00, 0x57, 0x7a, 0x50, 0x4f, 0x17, 0x25, 0xfd, 0x85,
	0x00, 0xdf, 0xb6, 0x7d, 0xa3, 0x1f, 0xe4, 0xa3, 0x26, 0x0e, 0xca, 0x0c, 0xf6, 0x7e, 0xd1, 0x38,
	0xf3, 0xe4, 0x8b, 0xeb, 0x7e, 0x03, 0x59, 0xc3, 0xa6, 0xdb, 0xd0, 0x1b, 0x3b, 0xe0, 0x2f, 0x77,
	0xb0, 0xed, 0xa3, 0xd4, 0xc5, 0x8c, 0x26, 0x74, 0x1a, 0x41, 0xf2, 0x6f, 0x04, 0xf4, 0x0d, 0xa4,
	0x9f, 0xa5, 0x3d, 0x6a, 0x71, 0x8e, 0x55, 0xfa, 0x13, 0xc1, 0xa6, 0x96, 0x5c, 0xaa, 0xfe, 0x74,
	0xb6, 0x3b, 0xd8, 0xca, 0xe8, 0x71, 0x9e, 0x06, 0x4c, 0xe8, 0x9c, 0x71, 0xdc, 0x40, 0xd6, 0x7a,
	0x2d, 0xb3, 0x17, 0x1c, 0x40, 0x29, 0xc8, 0x2b, 0xc0, 0x82, 0x59, 0x69, 0x55, 0x2b, 0xbd, 0x8d,
	0xac, 0xfe, 0x5b, 0xd3, 0xdf, 0x08, 0x70, 0x35, 0x1a, 0x7e, 0x64, 0xc3, 0xa3, 0xf9, 0x9a, 0x20,
	0x79, 0xb1, 0x24, 0x91, 0x94, 0x82, 0xbc, 0x04, 0xec, 0xc7, 0x3e, 0x4b, 0xda, 0xf8, 0x3a, 0x2c,
	0x38, 0x6b, 0xf5, 0xd8, 0xd9, 0xb8, 0x1f, 0xb1, 0x9a, 0xd7, 0x26, 0x59, 0xac, 0x8d, 0x7b, 0x6d,
	0xe4, 0x30, 0x36, 0x36, 0x4f, 0xc3, 0xeb, 0x50, 0x7d, 0x4d, 0xfd, 0x5f, 0xca, 0xfb, 0x3f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x92, 0xd2, 0xb8, 0xa5, 0x6d, 0x04, 0x00, 0x00,
}
