// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/reader/reader.proto

package reader

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	model "github.com/methrilion/gourmet/proto/model"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListCurrencyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCurrencyRequest) Reset()         { *m = ListCurrencyRequest{} }
func (m *ListCurrencyRequest) String() string { return proto.CompactTextString(m) }
func (*ListCurrencyRequest) ProtoMessage()    {}
func (*ListCurrencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{0}
}

func (m *ListCurrencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCurrencyRequest.Unmarshal(m, b)
}
func (m *ListCurrencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCurrencyRequest.Marshal(b, m, deterministic)
}
func (m *ListCurrencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCurrencyRequest.Merge(m, src)
}
func (m *ListCurrencyRequest) XXX_Size() int {
	return xxx_messageInfo_ListCurrencyRequest.Size(m)
}
func (m *ListCurrencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCurrencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCurrencyRequest proto.InternalMessageInfo

type ListCurrencyResponse struct {
	Currency             []*model.Currency `protobuf:"bytes,1,rep,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListCurrencyResponse) Reset()         { *m = ListCurrencyResponse{} }
func (m *ListCurrencyResponse) String() string { return proto.CompactTextString(m) }
func (*ListCurrencyResponse) ProtoMessage()    {}
func (*ListCurrencyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{1}
}

func (m *ListCurrencyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCurrencyResponse.Unmarshal(m, b)
}
func (m *ListCurrencyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCurrencyResponse.Marshal(b, m, deterministic)
}
func (m *ListCurrencyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCurrencyResponse.Merge(m, src)
}
func (m *ListCurrencyResponse) XXX_Size() int {
	return xxx_messageInfo_ListCurrencyResponse.Size(m)
}
func (m *ListCurrencyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCurrencyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCurrencyResponse proto.InternalMessageInfo

func (m *ListCurrencyResponse) GetCurrency() []*model.Currency {
	if m != nil {
		return m.Currency
	}
	return nil
}

type GetCurrencyRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrencyRequest) Reset()         { *m = GetCurrencyRequest{} }
func (m *GetCurrencyRequest) String() string { return proto.CompactTextString(m) }
func (*GetCurrencyRequest) ProtoMessage()    {}
func (*GetCurrencyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{2}
}

func (m *GetCurrencyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrencyRequest.Unmarshal(m, b)
}
func (m *GetCurrencyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrencyRequest.Marshal(b, m, deterministic)
}
func (m *GetCurrencyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrencyRequest.Merge(m, src)
}
func (m *GetCurrencyRequest) XXX_Size() int {
	return xxx_messageInfo_GetCurrencyRequest.Size(m)
}
func (m *GetCurrencyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrencyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrencyRequest proto.InternalMessageInfo

func (m *GetCurrencyRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListRatesOfExchangeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRatesOfExchangeRequest) Reset()         { *m = ListRatesOfExchangeRequest{} }
func (m *ListRatesOfExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*ListRatesOfExchangeRequest) ProtoMessage()    {}
func (*ListRatesOfExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{3}
}

func (m *ListRatesOfExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRatesOfExchangeRequest.Unmarshal(m, b)
}
func (m *ListRatesOfExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRatesOfExchangeRequest.Marshal(b, m, deterministic)
}
func (m *ListRatesOfExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRatesOfExchangeRequest.Merge(m, src)
}
func (m *ListRatesOfExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_ListRatesOfExchangeRequest.Size(m)
}
func (m *ListRatesOfExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRatesOfExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRatesOfExchangeRequest proto.InternalMessageInfo

type ListRatesOfExchangeResponse struct {
	RatesOfExchange      []*model.RateOfExchange `protobuf:"bytes,1,rep,name=rates_of_exchange,json=ratesOfExchange,proto3" json:"rates_of_exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ListRatesOfExchangeResponse) Reset()         { *m = ListRatesOfExchangeResponse{} }
func (m *ListRatesOfExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*ListRatesOfExchangeResponse) ProtoMessage()    {}
func (*ListRatesOfExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{4}
}

func (m *ListRatesOfExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRatesOfExchangeResponse.Unmarshal(m, b)
}
func (m *ListRatesOfExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRatesOfExchangeResponse.Marshal(b, m, deterministic)
}
func (m *ListRatesOfExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRatesOfExchangeResponse.Merge(m, src)
}
func (m *ListRatesOfExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_ListRatesOfExchangeResponse.Size(m)
}
func (m *ListRatesOfExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRatesOfExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRatesOfExchangeResponse proto.InternalMessageInfo

func (m *ListRatesOfExchangeResponse) GetRatesOfExchange() []*model.RateOfExchange {
	if m != nil {
		return m.RatesOfExchange
	}
	return nil
}

type GetRateOfExchangeRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRateOfExchangeRequest) Reset()         { *m = GetRateOfExchangeRequest{} }
func (m *GetRateOfExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*GetRateOfExchangeRequest) ProtoMessage()    {}
func (*GetRateOfExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{5}
}

func (m *GetRateOfExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRateOfExchangeRequest.Unmarshal(m, b)
}
func (m *GetRateOfExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRateOfExchangeRequest.Marshal(b, m, deterministic)
}
func (m *GetRateOfExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRateOfExchangeRequest.Merge(m, src)
}
func (m *GetRateOfExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_GetRateOfExchangeRequest.Size(m)
}
func (m *GetRateOfExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRateOfExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRateOfExchangeRequest proto.InternalMessageInfo

func (m *GetRateOfExchangeRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListLocationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListLocationsRequest) Reset()         { *m = ListLocationsRequest{} }
func (m *ListLocationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListLocationsRequest) ProtoMessage()    {}
func (*ListLocationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{6}
}

func (m *ListLocationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLocationsRequest.Unmarshal(m, b)
}
func (m *ListLocationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLocationsRequest.Marshal(b, m, deterministic)
}
func (m *ListLocationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLocationsRequest.Merge(m, src)
}
func (m *ListLocationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListLocationsRequest.Size(m)
}
func (m *ListLocationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLocationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListLocationsRequest proto.InternalMessageInfo

type ListLocationsResponse struct {
	Locations            []*model.Location `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListLocationsResponse) Reset()         { *m = ListLocationsResponse{} }
func (m *ListLocationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListLocationsResponse) ProtoMessage()    {}
func (*ListLocationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{7}
}

func (m *ListLocationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListLocationsResponse.Unmarshal(m, b)
}
func (m *ListLocationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListLocationsResponse.Marshal(b, m, deterministic)
}
func (m *ListLocationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListLocationsResponse.Merge(m, src)
}
func (m *ListLocationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListLocationsResponse.Size(m)
}
func (m *ListLocationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListLocationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListLocationsResponse proto.InternalMessageInfo

func (m *ListLocationsResponse) GetLocations() []*model.Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

type GetLocationRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLocationRequest) Reset()         { *m = GetLocationRequest{} }
func (m *GetLocationRequest) String() string { return proto.CompactTextString(m) }
func (*GetLocationRequest) ProtoMessage()    {}
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{8}
}

func (m *GetLocationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLocationRequest.Unmarshal(m, b)
}
func (m *GetLocationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLocationRequest.Marshal(b, m, deterministic)
}
func (m *GetLocationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLocationRequest.Merge(m, src)
}
func (m *GetLocationRequest) XXX_Size() int {
	return xxx_messageInfo_GetLocationRequest.Size(m)
}
func (m *GetLocationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLocationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLocationRequest proto.InternalMessageInfo

func (m *GetLocationRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListProductsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProductsRequest) Reset()         { *m = ListProductsRequest{} }
func (m *ListProductsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProductsRequest) ProtoMessage()    {}
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{9}
}

func (m *ListProductsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsRequest.Unmarshal(m, b)
}
func (m *ListProductsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsRequest.Marshal(b, m, deterministic)
}
func (m *ListProductsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsRequest.Merge(m, src)
}
func (m *ListProductsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProductsRequest.Size(m)
}
func (m *ListProductsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsRequest proto.InternalMessageInfo

type ListProductsResponse struct {
	Products             []*model.Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListProductsResponse) Reset()         { *m = ListProductsResponse{} }
func (m *ListProductsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProductsResponse) ProtoMessage()    {}
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{10}
}

func (m *ListProductsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProductsResponse.Unmarshal(m, b)
}
func (m *ListProductsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProductsResponse.Marshal(b, m, deterministic)
}
func (m *ListProductsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProductsResponse.Merge(m, src)
}
func (m *ListProductsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProductsResponse.Size(m)
}
func (m *ListProductsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProductsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProductsResponse proto.InternalMessageInfo

func (m *ListProductsResponse) GetProducts() []*model.Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type GetProductRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductRequest) Reset()         { *m = GetProductRequest{} }
func (m *GetProductRequest) String() string { return proto.CompactTextString(m) }
func (*GetProductRequest) ProtoMessage()    {}
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{11}
}

func (m *GetProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductRequest.Unmarshal(m, b)
}
func (m *GetProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductRequest.Marshal(b, m, deterministic)
}
func (m *GetProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductRequest.Merge(m, src)
}
func (m *GetProductRequest) XXX_Size() int {
	return xxx_messageInfo_GetProductRequest.Size(m)
}
func (m *GetProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductRequest proto.InternalMessageInfo

func (m *GetProductRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListPricesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPricesRequest) Reset()         { *m = ListPricesRequest{} }
func (m *ListPricesRequest) String() string { return proto.CompactTextString(m) }
func (*ListPricesRequest) ProtoMessage()    {}
func (*ListPricesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{12}
}

func (m *ListPricesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPricesRequest.Unmarshal(m, b)
}
func (m *ListPricesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPricesRequest.Marshal(b, m, deterministic)
}
func (m *ListPricesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPricesRequest.Merge(m, src)
}
func (m *ListPricesRequest) XXX_Size() int {
	return xxx_messageInfo_ListPricesRequest.Size(m)
}
func (m *ListPricesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPricesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPricesRequest proto.InternalMessageInfo

type ListPricesResponse struct {
	Prices               []*model.Price `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListPricesResponse) Reset()         { *m = ListPricesResponse{} }
func (m *ListPricesResponse) String() string { return proto.CompactTextString(m) }
func (*ListPricesResponse) ProtoMessage()    {}
func (*ListPricesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{13}
}

func (m *ListPricesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPricesResponse.Unmarshal(m, b)
}
func (m *ListPricesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPricesResponse.Marshal(b, m, deterministic)
}
func (m *ListPricesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPricesResponse.Merge(m, src)
}
func (m *ListPricesResponse) XXX_Size() int {
	return xxx_messageInfo_ListPricesResponse.Size(m)
}
func (m *ListPricesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPricesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPricesResponse proto.InternalMessageInfo

func (m *ListPricesResponse) GetPrices() []*model.Price {
	if m != nil {
		return m.Prices
	}
	return nil
}

type GetPriceRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPriceRequest) Reset()         { *m = GetPriceRequest{} }
func (m *GetPriceRequest) String() string { return proto.CompactTextString(m) }
func (*GetPriceRequest) ProtoMessage()    {}
func (*GetPriceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{14}
}

func (m *GetPriceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPriceRequest.Unmarshal(m, b)
}
func (m *GetPriceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPriceRequest.Marshal(b, m, deterministic)
}
func (m *GetPriceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPriceRequest.Merge(m, src)
}
func (m *GetPriceRequest) XXX_Size() int {
	return xxx_messageInfo_GetPriceRequest.Size(m)
}
func (m *GetPriceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPriceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPriceRequest proto.InternalMessageInfo

func (m *GetPriceRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListPositionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPositionsRequest) Reset()         { *m = ListPositionsRequest{} }
func (m *ListPositionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPositionsRequest) ProtoMessage()    {}
func (*ListPositionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{15}
}

func (m *ListPositionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPositionsRequest.Unmarshal(m, b)
}
func (m *ListPositionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPositionsRequest.Marshal(b, m, deterministic)
}
func (m *ListPositionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPositionsRequest.Merge(m, src)
}
func (m *ListPositionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPositionsRequest.Size(m)
}
func (m *ListPositionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPositionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPositionsRequest proto.InternalMessageInfo

type ListPositionsResponse struct {
	Positions            []*model.Position `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListPositionsResponse) Reset()         { *m = ListPositionsResponse{} }
func (m *ListPositionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPositionsResponse) ProtoMessage()    {}
func (*ListPositionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{16}
}

func (m *ListPositionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPositionsResponse.Unmarshal(m, b)
}
func (m *ListPositionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPositionsResponse.Marshal(b, m, deterministic)
}
func (m *ListPositionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPositionsResponse.Merge(m, src)
}
func (m *ListPositionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPositionsResponse.Size(m)
}
func (m *ListPositionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPositionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPositionsResponse proto.InternalMessageInfo

func (m *ListPositionsResponse) GetPositions() []*model.Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

type GetPositionRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPositionRequest) Reset()         { *m = GetPositionRequest{} }
func (m *GetPositionRequest) String() string { return proto.CompactTextString(m) }
func (*GetPositionRequest) ProtoMessage()    {}
func (*GetPositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{17}
}

func (m *GetPositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPositionRequest.Unmarshal(m, b)
}
func (m *GetPositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPositionRequest.Marshal(b, m, deterministic)
}
func (m *GetPositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPositionRequest.Merge(m, src)
}
func (m *GetPositionRequest) XXX_Size() int {
	return xxx_messageInfo_GetPositionRequest.Size(m)
}
func (m *GetPositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPositionRequest proto.InternalMessageInfo

func (m *GetPositionRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListEmployeesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListEmployeesRequest) Reset()         { *m = ListEmployeesRequest{} }
func (m *ListEmployeesRequest) String() string { return proto.CompactTextString(m) }
func (*ListEmployeesRequest) ProtoMessage()    {}
func (*ListEmployeesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{18}
}

func (m *ListEmployeesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEmployeesRequest.Unmarshal(m, b)
}
func (m *ListEmployeesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEmployeesRequest.Marshal(b, m, deterministic)
}
func (m *ListEmployeesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEmployeesRequest.Merge(m, src)
}
func (m *ListEmployeesRequest) XXX_Size() int {
	return xxx_messageInfo_ListEmployeesRequest.Size(m)
}
func (m *ListEmployeesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEmployeesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListEmployeesRequest proto.InternalMessageInfo

type ListEmployeesResponse struct {
	Employees            []*model.Employee `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListEmployeesResponse) Reset()         { *m = ListEmployeesResponse{} }
func (m *ListEmployeesResponse) String() string { return proto.CompactTextString(m) }
func (*ListEmployeesResponse) ProtoMessage()    {}
func (*ListEmployeesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{19}
}

func (m *ListEmployeesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListEmployeesResponse.Unmarshal(m, b)
}
func (m *ListEmployeesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListEmployeesResponse.Marshal(b, m, deterministic)
}
func (m *ListEmployeesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListEmployeesResponse.Merge(m, src)
}
func (m *ListEmployeesResponse) XXX_Size() int {
	return xxx_messageInfo_ListEmployeesResponse.Size(m)
}
func (m *ListEmployeesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListEmployeesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListEmployeesResponse proto.InternalMessageInfo

func (m *ListEmployeesResponse) GetEmployees() []*model.Employee {
	if m != nil {
		return m.Employees
	}
	return nil
}

type GetEmployeeRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEmployeeRequest) Reset()         { *m = GetEmployeeRequest{} }
func (m *GetEmployeeRequest) String() string { return proto.CompactTextString(m) }
func (*GetEmployeeRequest) ProtoMessage()    {}
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{20}
}

func (m *GetEmployeeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEmployeeRequest.Unmarshal(m, b)
}
func (m *GetEmployeeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEmployeeRequest.Marshal(b, m, deterministic)
}
func (m *GetEmployeeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEmployeeRequest.Merge(m, src)
}
func (m *GetEmployeeRequest) XXX_Size() int {
	return xxx_messageInfo_GetEmployeeRequest.Size(m)
}
func (m *GetEmployeeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEmployeeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEmployeeRequest proto.InternalMessageInfo

func (m *GetEmployeeRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListMethodsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListMethodsRequest) Reset()         { *m = ListMethodsRequest{} }
func (m *ListMethodsRequest) String() string { return proto.CompactTextString(m) }
func (*ListMethodsRequest) ProtoMessage()    {}
func (*ListMethodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{21}
}

func (m *ListMethodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMethodsRequest.Unmarshal(m, b)
}
func (m *ListMethodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMethodsRequest.Marshal(b, m, deterministic)
}
func (m *ListMethodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMethodsRequest.Merge(m, src)
}
func (m *ListMethodsRequest) XXX_Size() int {
	return xxx_messageInfo_ListMethodsRequest.Size(m)
}
func (m *ListMethodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMethodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListMethodsRequest proto.InternalMessageInfo

type ListMethodsResponse struct {
	Methods              []*model.Method `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListMethodsResponse) Reset()         { *m = ListMethodsResponse{} }
func (m *ListMethodsResponse) String() string { return proto.CompactTextString(m) }
func (*ListMethodsResponse) ProtoMessage()    {}
func (*ListMethodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{22}
}

func (m *ListMethodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListMethodsResponse.Unmarshal(m, b)
}
func (m *ListMethodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListMethodsResponse.Marshal(b, m, deterministic)
}
func (m *ListMethodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListMethodsResponse.Merge(m, src)
}
func (m *ListMethodsResponse) XXX_Size() int {
	return xxx_messageInfo_ListMethodsResponse.Size(m)
}
func (m *ListMethodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListMethodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListMethodsResponse proto.InternalMessageInfo

func (m *ListMethodsResponse) GetMethods() []*model.Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

type GetMethodRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMethodRequest) Reset()         { *m = GetMethodRequest{} }
func (m *GetMethodRequest) String() string { return proto.CompactTextString(m) }
func (*GetMethodRequest) ProtoMessage()    {}
func (*GetMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{23}
}

func (m *GetMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMethodRequest.Unmarshal(m, b)
}
func (m *GetMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMethodRequest.Marshal(b, m, deterministic)
}
func (m *GetMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMethodRequest.Merge(m, src)
}
func (m *GetMethodRequest) XXX_Size() int {
	return xxx_messageInfo_GetMethodRequest.Size(m)
}
func (m *GetMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMethodRequest proto.InternalMessageInfo

func (m *GetMethodRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListReceiptsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListReceiptsRequest) Reset()         { *m = ListReceiptsRequest{} }
func (m *ListReceiptsRequest) String() string { return proto.CompactTextString(m) }
func (*ListReceiptsRequest) ProtoMessage()    {}
func (*ListReceiptsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{24}
}

func (m *ListReceiptsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReceiptsRequest.Unmarshal(m, b)
}
func (m *ListReceiptsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReceiptsRequest.Marshal(b, m, deterministic)
}
func (m *ListReceiptsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReceiptsRequest.Merge(m, src)
}
func (m *ListReceiptsRequest) XXX_Size() int {
	return xxx_messageInfo_ListReceiptsRequest.Size(m)
}
func (m *ListReceiptsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReceiptsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListReceiptsRequest proto.InternalMessageInfo

type ListReceiptsResponse struct {
	Receipts             []*model.Receipt `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListReceiptsResponse) Reset()         { *m = ListReceiptsResponse{} }
func (m *ListReceiptsResponse) String() string { return proto.CompactTextString(m) }
func (*ListReceiptsResponse) ProtoMessage()    {}
func (*ListReceiptsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{25}
}

func (m *ListReceiptsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReceiptsResponse.Unmarshal(m, b)
}
func (m *ListReceiptsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReceiptsResponse.Marshal(b, m, deterministic)
}
func (m *ListReceiptsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReceiptsResponse.Merge(m, src)
}
func (m *ListReceiptsResponse) XXX_Size() int {
	return xxx_messageInfo_ListReceiptsResponse.Size(m)
}
func (m *ListReceiptsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReceiptsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListReceiptsResponse proto.InternalMessageInfo

func (m *ListReceiptsResponse) GetReceipts() []*model.Receipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

type GetReceiptRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReceiptRequest) Reset()         { *m = GetReceiptRequest{} }
func (m *GetReceiptRequest) String() string { return proto.CompactTextString(m) }
func (*GetReceiptRequest) ProtoMessage()    {}
func (*GetReceiptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{26}
}

func (m *GetReceiptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReceiptRequest.Unmarshal(m, b)
}
func (m *GetReceiptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReceiptRequest.Marshal(b, m, deterministic)
}
func (m *GetReceiptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReceiptRequest.Merge(m, src)
}
func (m *GetReceiptRequest) XXX_Size() int {
	return xxx_messageInfo_GetReceiptRequest.Size(m)
}
func (m *GetReceiptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReceiptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReceiptRequest proto.InternalMessageInfo

func (m *GetReceiptRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListPurchasesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPurchasesRequest) Reset()         { *m = ListPurchasesRequest{} }
func (m *ListPurchasesRequest) String() string { return proto.CompactTextString(m) }
func (*ListPurchasesRequest) ProtoMessage()    {}
func (*ListPurchasesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{27}
}

func (m *ListPurchasesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPurchasesRequest.Unmarshal(m, b)
}
func (m *ListPurchasesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPurchasesRequest.Marshal(b, m, deterministic)
}
func (m *ListPurchasesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPurchasesRequest.Merge(m, src)
}
func (m *ListPurchasesRequest) XXX_Size() int {
	return xxx_messageInfo_ListPurchasesRequest.Size(m)
}
func (m *ListPurchasesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPurchasesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPurchasesRequest proto.InternalMessageInfo

type ListPurchasesResponse struct {
	Purchases            []*model.Purchase `protobuf:"bytes,1,rep,name=purchases,proto3" json:"purchases,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListPurchasesResponse) Reset()         { *m = ListPurchasesResponse{} }
func (m *ListPurchasesResponse) String() string { return proto.CompactTextString(m) }
func (*ListPurchasesResponse) ProtoMessage()    {}
func (*ListPurchasesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{28}
}

func (m *ListPurchasesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPurchasesResponse.Unmarshal(m, b)
}
func (m *ListPurchasesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPurchasesResponse.Marshal(b, m, deterministic)
}
func (m *ListPurchasesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPurchasesResponse.Merge(m, src)
}
func (m *ListPurchasesResponse) XXX_Size() int {
	return xxx_messageInfo_ListPurchasesResponse.Size(m)
}
func (m *ListPurchasesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPurchasesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPurchasesResponse proto.InternalMessageInfo

func (m *ListPurchasesResponse) GetPurchases() []*model.Purchase {
	if m != nil {
		return m.Purchases
	}
	return nil
}

type GetPurchaseRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPurchaseRequest) Reset()         { *m = GetPurchaseRequest{} }
func (m *GetPurchaseRequest) String() string { return proto.CompactTextString(m) }
func (*GetPurchaseRequest) ProtoMessage()    {}
func (*GetPurchaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed0bf67d7f67361a, []int{29}
}

func (m *GetPurchaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPurchaseRequest.Unmarshal(m, b)
}
func (m *GetPurchaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPurchaseRequest.Marshal(b, m, deterministic)
}
func (m *GetPurchaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPurchaseRequest.Merge(m, src)
}
func (m *GetPurchaseRequest) XXX_Size() int {
	return xxx_messageInfo_GetPurchaseRequest.Size(m)
}
func (m *GetPurchaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPurchaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPurchaseRequest proto.InternalMessageInfo

func (m *GetPurchaseRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*ListCurrencyRequest)(nil), "reader.ListCurrencyRequest")
	proto.RegisterType((*ListCurrencyResponse)(nil), "reader.ListCurrencyResponse")
	proto.RegisterType((*GetCurrencyRequest)(nil), "reader.GetCurrencyRequest")
	proto.RegisterType((*ListRatesOfExchangeRequest)(nil), "reader.ListRatesOfExchangeRequest")
	proto.RegisterType((*ListRatesOfExchangeResponse)(nil), "reader.ListRatesOfExchangeResponse")
	proto.RegisterType((*GetRateOfExchangeRequest)(nil), "reader.GetRateOfExchangeRequest")
	proto.RegisterType((*ListLocationsRequest)(nil), "reader.ListLocationsRequest")
	proto.RegisterType((*ListLocationsResponse)(nil), "reader.ListLocationsResponse")
	proto.RegisterType((*GetLocationRequest)(nil), "reader.GetLocationRequest")
	proto.RegisterType((*ListProductsRequest)(nil), "reader.ListProductsRequest")
	proto.RegisterType((*ListProductsResponse)(nil), "reader.ListProductsResponse")
	proto.RegisterType((*GetProductRequest)(nil), "reader.GetProductRequest")
	proto.RegisterType((*ListPricesRequest)(nil), "reader.ListPricesRequest")
	proto.RegisterType((*ListPricesResponse)(nil), "reader.ListPricesResponse")
	proto.RegisterType((*GetPriceRequest)(nil), "reader.GetPriceRequest")
	proto.RegisterType((*ListPositionsRequest)(nil), "reader.ListPositionsRequest")
	proto.RegisterType((*ListPositionsResponse)(nil), "reader.ListPositionsResponse")
	proto.RegisterType((*GetPositionRequest)(nil), "reader.GetPositionRequest")
	proto.RegisterType((*ListEmployeesRequest)(nil), "reader.ListEmployeesRequest")
	proto.RegisterType((*ListEmployeesResponse)(nil), "reader.ListEmployeesResponse")
	proto.RegisterType((*GetEmployeeRequest)(nil), "reader.GetEmployeeRequest")
	proto.RegisterType((*ListMethodsRequest)(nil), "reader.ListMethodsRequest")
	proto.RegisterType((*ListMethodsResponse)(nil), "reader.ListMethodsResponse")
	proto.RegisterType((*GetMethodRequest)(nil), "reader.GetMethodRequest")
	proto.RegisterType((*ListReceiptsRequest)(nil), "reader.ListReceiptsRequest")
	proto.RegisterType((*ListReceiptsResponse)(nil), "reader.ListReceiptsResponse")
	proto.RegisterType((*GetReceiptRequest)(nil), "reader.GetReceiptRequest")
	proto.RegisterType((*ListPurchasesRequest)(nil), "reader.ListPurchasesRequest")
	proto.RegisterType((*ListPurchasesResponse)(nil), "reader.ListPurchasesResponse")
	proto.RegisterType((*GetPurchaseRequest)(nil), "reader.GetPurchaseRequest")
}

func init() { proto.RegisterFile("proto/reader/reader.proto", fileDescriptor_ed0bf67d7f67361a) }

var fileDescriptor_ed0bf67d7f67361a = []byte{
	// 971 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x57, 0x51, 0x6f, 0x1b, 0x45,
	0x10, 0x56, 0x82, 0x94, 0x26, 0x93, 0xc4, 0x8e, 0xa7, 0x76, 0xe3, 0x6c, 0x82, 0x08, 0xdb, 0x4a,
	0x54, 0x45, 0xf8, 0xa4, 0x22, 0x5e, 0x78, 0x40, 0x82, 0xaa, 0xf8, 0x81, 0xa2, 0x56, 0x17, 0x1e,
	0x78, 0x40, 0x6a, 0xaf, 0xe7, 0xad, 0x7d, 0x92, 0xed, 0x3d, 0xee, 0xce, 0x88, 0x82, 0x78, 0xe1,
	0x2f, 0xf0, 0x53, 0xf8, 0x29, 0xfc, 0x05, 0x7e, 0x48, 0xe5, 0xdb, 0xd9, 0xbd, 0x9d, 0xbd, 0x73,
	0xf2, 0xd2, 0xca, 0x33, 0xb3, 0x33, 0xdf, 0xcd, 0x7e, 0xfb, 0x7d, 0x0a, 0x5c, 0xe4, 0x85, 0xae,
	0x74, 0x54, 0xa8, 0x64, 0xa6, 0x0a, 0xfa, 0x6f, 0x52, 0xc7, 0xf0, 0xc0, 0xfc, 0x12, 0x5f, 0xcd,
	0xb3, 0x6a, 0xb1, 0x79, 0x3b, 0x49, 0xf5, 0x2a, 0x5a, 0xa9, 0x6a, 0x51, 0x64, 0xcb, 0x4c, 0xaf,
	0xa3, 0xb9, 0xde, 0x14, 0x2b, 0x55, 0x45, 0xa6, 0xc1, 0x4a, 0xcf, 0xd4, 0xd2, 0xfc, 0x6b, 0x8e,
	0x8b, 0xab, 0xb9, 0xd6, 0xf3, 0xa5, 0x8a, 0x92, 0x3c, 0x8b, 0x92, 0xf5, 0x5a, 0x57, 0x49, 0x95,
	0xe9, 0x75, 0x69, 0xb2, 0x72, 0x04, 0xf7, 0x5f, 0x64, 0x65, 0xf5, 0x6c, 0x53, 0x14, 0x6a, 0x9d,
	0xbe, 0x8f, 0xd5, 0xaf, 0x1b, 0x55, 0x56, 0xf2, 0x19, 0x0c, 0x79, 0xb8, 0xcc, 0xf5, 0xba, 0x54,
	0xf8, 0x39, 0x1c, 0xa6, 0x14, 0x1b, 0xef, 0x5d, 0x7f, 0xf4, 0xf8, 0xf8, 0x69, 0x7f, 0x62, 0x86,
	0xb9, 0x52, 0x57, 0x20, 0x1f, 0x01, 0x4e, 0x55, 0xd8, 0x1a, 0x7b, 0xb0, 0x9f, 0xcd, 0xc6, 0x7b,
	0xd7, 0x7b, 0x8f, 0x4f, 0xe3, 0xfd, 0x6c, 0x26, 0xaf, 0x40, 0x6c, 0x47, 0xc5, 0x49, 0xa5, 0xca,
	0x97, 0xef, 0x9e, 0xff, 0x9e, 0x2e, 0x92, 0xf5, 0x5c, 0x59, 0x20, 0x6f, 0xe0, 0xb2, 0x33, 0x4b,
	0x78, 0xbe, 0x85, 0x41, 0xb1, 0x4d, 0xbd, 0xd6, 0xef, 0x5e, 0x2b, 0x4a, 0x12, 0xb0, 0x11, 0x01,
	0xdb, 0x1e, 0xf5, 0x4e, 0xf6, 0x0b, 0xde, 0x4a, 0x3e, 0x81, 0xf1, 0x54, 0x55, 0x41, 0xd5, 0x0e,
	0xac, 0x0f, 0xcc, 0x5a, 0x5e, 0xe8, 0xd4, 0x2c, 0xd1, 0xa2, 0xfc, 0x1e, 0x46, 0x41, 0x9c, 0xf0,
	0x7d, 0x01, 0x47, 0x4b, 0x1b, 0x0c, 0x16, 0x66, 0x8b, 0xe3, 0xa6, 0x82, 0x36, 0xe6, 0x32, 0x3b,
	0x50, 0xd0, 0x9d, 0xbd, 0x2a, 0xf4, 0x6c, 0x93, 0x56, 0x0e, 0xc4, 0x77, 0x06, 0x5c, 0x13, 0x26,
	0x0c, 0x4f, 0xe0, 0x30, 0xa7, 0x18, 0x41, 0xe8, 0x11, 0x04, 0x2a, 0x8d, 0x5d, 0x5e, 0x3e, 0x84,
	0xc1, 0x54, 0xd9, 0x16, 0xbb, 0xe6, 0xdf, 0x87, 0x81, 0x19, 0x94, 0xa5, 0xca, 0x4d, 0xff, 0x1a,
	0xd0, 0x0f, 0xd2, 0xec, 0x47, 0x70, 0x90, 0xd7, 0x11, 0x9a, 0x7c, 0xe2, 0x26, 0x67, 0xa9, 0x8a,
	0x29, 0x27, 0x3f, 0x85, 0x7e, 0x3d, 0x75, 0x1b, 0xbb, 0x7d, 0xf3, 0xaf, 0x74, 0x99, 0x75, 0x6d,
	0xde, 0x8b, 0x37, 0x9b, 0xcf, 0x6d, 0x30, 0xd8, 0xbc, 0x2d, 0x8e, 0x9b, 0x0a, 0xda, 0xbc, 0xcb,
	0xdc, 0x8e, 0xe2, 0xf9, 0x2a, 0x5f, 0xea, 0xf7, 0x4a, 0x85, 0x28, 0xbc, 0x78, 0x83, 0x42, 0xd9,
	0x60, 0x80, 0xc2, 0x16, 0xc7, 0x4d, 0x05, 0xa1, 0x70, 0x99, 0x1d, 0x28, 0x86, 0x66, 0xd5, 0x3f,
	0xaa, 0x6a, 0xa1, 0x67, 0x0e, 0xc3, 0x37, 0x86, 0x15, 0x2e, 0x4a, 0x08, 0x3e, 0x83, 0x7b, 0x2b,
	0x13, 0xa2, 0xf9, 0xa7, 0x34, 0xdf, 0x14, 0xc6, 0x36, 0x2b, 0x25, 0x9c, 0x4d, 0x15, 0x1d, 0xbf,
	0x83, 0x79, 0xb1, 0x4a, 0x55, 0x96, 0xb7, 0x98, 0xd7, 0x84, 0x1b, 0xe6, 0x15, 0x14, 0x0b, 0x98,
	0x47, 0xa5, 0xb1, 0xcb, 0x13, 0xf3, 0x6c, 0xfc, 0x0e, 0x16, 0x6c, 0x8a, 0x74, 0x91, 0x94, 0xad,
	0xfd, 0x7b, 0x71, 0x8f, 0x05, 0x36, 0x18, 0xb2, 0x80, 0xe2, 0x71, 0x53, 0x61, 0x59, 0x60, 0x33,
	0xdd, 0x28, 0x9e, 0xfe, 0xdb, 0x83, 0xe1, 0x4d, 0xa5, 0x8b, 0x64, 0x2b, 0x14, 0x5b, 0x69, 0xbe,
	0x51, 0xc5, 0x6f, 0x59, 0xaa, 0xf0, 0x17, 0x38, 0xf1, 0x55, 0x13, 0x2f, 0x27, 0x24, 0xe4, 0x1d,
	0x12, 0x2b, 0xae, 0xba, 0x93, 0x06, 0xb8, 0x1c, 0xfc, 0xfd, 0xdf, 0xff, 0xff, 0xec, 0x1f, 0xe3,
	0x51, 0x64, 0xe5, 0x14, 0x63, 0x38, 0xf6, 0xe4, 0x14, 0x85, 0x3d, 0xdf, 0xd6, 0x58, 0x11, 0x8a,
	0xb2, 0x7c, 0x50, 0xb7, 0x3b, 0xc3, 0x9e, 0x6b, 0x17, 0xfd, 0x99, 0xcd, 0xfe, 0xc2, 0x3f, 0xe8,
	0x42, 0xb9, 0x26, 0xa2, 0xf4, 0xb1, 0x75, 0x2b, 0xb3, 0x78, 0x78, 0x6b, 0x0d, 0x7d, 0x86, 0xa8,
	0xe7, 0x0e, 0x11, 0xa3, 0x96, 0x4c, 0xe3, 0xca, 0xdc, 0x38, 0x13, 0x5e, 0xbc, 0xf6, 0xbe, 0xaa,
	0x53, 0x93, 0x45, 0xb7, 0xae, 0xcb, 0x4f, 0xea, 0x49, 0x17, 0x78, 0xde, 0x9e, 0x64, 0x3e, 0xf5,
	0x0d, 0x9c, 0x32, 0x8d, 0x46, 0x76, 0x01, 0xa1, 0xa4, 0x8b, 0x8f, 0x77, 0x64, 0xe9, 0xc3, 0xb0,
	0x1e, 0x77, 0x82, 0x10, 0x39, 0xf5, 0xc6, 0x9b, 0xfa, 0x82, 0x6c, 0x2d, 0xbb, 0xa0, 0x40, 0xd2,
	0x45, 0x68, 0x02, 0xf2, 0xbc, 0xee, 0x37, 0xc0, 0x7e, 0xd3, 0xcf, 0xc0, 0x26, 0x4e, 0x59, 0x55,
	0xe7, 0x9c, 0x0a, 0x2c, 0x80, 0x73, 0x2a, 0x34, 0x02, 0x8f, 0x53, 0x56, 0xef, 0xf1, 0x25, 0x40,
	0xa3, 0xf7, 0x78, 0xe1, 0x21, 0xe6, 0x1e, 0x20, 0x02, 0xcb, 0xf0, 0x08, 0x65, 0x7b, 0x19, 0xb8,
	0x3f, 0x01, 0x34, 0x36, 0xd0, 0x34, 0x6c, 0xf9, 0x85, 0x10, 0x5d, 0x29, 0x02, 0xda, 0xaf, 0x9b,
	0x1f, 0xe1, 0xbd, 0xc8, 0x18, 0x04, 0x4e, 0xe1, 0xd0, 0x1a, 0x04, 0x9e, 0x33, 0x90, 0x8d, 0x65,
	0x08, 0xe6, 0x2d, 0x72, 0x58, 0xf7, 0xe8, 0xe1, 0x09, 0xf5, 0x60, 0x24, 0x70, 0x76, 0xc1, 0x49,
	0x10, 0xba, 0x0b, 0x27, 0x41, 0xcb, 0x63, 0x3c, 0x12, 0x38, 0x23, 0x21, 0x12, 0xd8, 0x5a, 0x46,
	0x82, 0xc0, 0x5d, 0x44, 0xe8, 0x47, 0x1e, 0x09, 0x5c, 0x3f, 0x06, 0xdb, 0xf9, 0x0b, 0x87, 0x1d,
	0xda, 0x11, 0x87, 0xdd, 0x32, 0x25, 0x0f, 0xb6, 0x73, 0x1e, 0x82, 0x6d, 0x6b, 0x19, 0xec, 0xc0,
	0x8e, 0x44, 0x68, 0x60, 0x1e, 0x6c, 0xd7, 0xcf, 0xc0, 0xfe, 0x19, 0x8e, 0x3d, 0x4b, 0x42, 0x76,
	0xe5, 0xdc, 0xbd, 0xc4, 0x65, 0x67, 0x8e, 0x00, 0x9f, 0xd5, 0x03, 0x00, 0x0f, 0x23, 0x32, 0x2b,
	0xfc, 0x01, 0x8e, 0x9c, 0x59, 0xe1, 0xd8, 0x03, 0xcb, 0xfc, 0x4b, 0x70, 0xaf, 0x93, 0xa3, 0xba,
	0x4f, 0x1f, 0x4f, 0x6d, 0x1f, 0xf6, 0xc4, 0xac, 0x7d, 0xf1, 0x27, 0x16, 0x78, 0x1d, 0x7f, 0x62,
	0xa1, 0xe3, 0x79, 0x4f, 0xcc, 0x1a, 0x1b, 0x3d, 0x31, 0xaa, 0x64, 0x4f, 0x8c, 0x9b, 0x9d, 0x08,
	0xbc, 0xd1, 0x7b, 0x62, 0xb6, 0x17, 0xe7, 0xb0, 0x75, 0xad, 0x80, 0xc3, 0x81, 0x37, 0x06, 0x1c,
	0x0e, 0x1d, 0xd2, 0xe7, 0xb0, 0x6b, 0x48, 0x1c, 0xa6, 0xdf, 0x9c, 0xc3, 0xdc, 0x1b, 0x45, 0xe8,
	0xa6, 0x3e, 0x87, 0x6d, 0xbf, 0x1a, 0xf6, 0xdb, 0x83, 0xfa, 0x0f, 0x8e, 0x2f, 0x3f, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xb6, 0x3f, 0x19, 0x3d, 0xea, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageReaderServiceClient is the client API for StorageReaderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageReaderServiceClient interface {
	ListCurrency(ctx context.Context, in *ListCurrencyRequest, opts ...grpc.CallOption) (*ListCurrencyResponse, error)
	GetCurrency(ctx context.Context, in *GetCurrencyRequest, opts ...grpc.CallOption) (*model.Currency, error)
	ListRatesOfExchange(ctx context.Context, in *ListRatesOfExchangeRequest, opts ...grpc.CallOption) (*ListRatesOfExchangeResponse, error)
	GetRateOfExchange(ctx context.Context, in *GetRateOfExchangeRequest, opts ...grpc.CallOption) (*model.RateOfExchange, error)
	ListLocations(ctx context.Context, in *ListLocationsRequest, opts ...grpc.CallOption) (*ListLocationsResponse, error)
	GetLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*model.Location, error)
	ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*model.Product, error)
	ListPrices(ctx context.Context, in *ListPricesRequest, opts ...grpc.CallOption) (*ListPricesResponse, error)
	GetPrice(ctx context.Context, in *GetPriceRequest, opts ...grpc.CallOption) (*model.Price, error)
	ListPositions(ctx context.Context, in *ListPositionsRequest, opts ...grpc.CallOption) (*ListPositionsResponse, error)
	GetPosition(ctx context.Context, in *GetPositionRequest, opts ...grpc.CallOption) (*model.Position, error)
	ListEmployees(ctx context.Context, in *ListEmployeesRequest, opts ...grpc.CallOption) (*ListEmployeesResponse, error)
	GetEmployee(ctx context.Context, in *GetEmployeeRequest, opts ...grpc.CallOption) (*model.Employee, error)
	ListMethods(ctx context.Context, in *ListMethodsRequest, opts ...grpc.CallOption) (*ListMethodsResponse, error)
	GetMethod(ctx context.Context, in *GetMethodRequest, opts ...grpc.CallOption) (*model.Method, error)
	ListReceipts(ctx context.Context, in *ListReceiptsRequest, opts ...grpc.CallOption) (*ListReceiptsResponse, error)
	GetReceipt(ctx context.Context, in *GetReceiptRequest, opts ...grpc.CallOption) (*model.Receipt, error)
	ListPurchases(ctx context.Context, in *ListPurchasesRequest, opts ...grpc.CallOption) (*ListPurchasesResponse, error)
	GetPurchase(ctx context.Context, in *GetPurchaseRequest, opts ...grpc.CallOption) (*model.Purchase, error)
}

type storageReaderServiceClient struct {
	cc *grpc.ClientConn
}

func NewStorageReaderServiceClient(cc *grpc.ClientConn) StorageReaderServiceClient {
	return &storageReaderServiceClient{cc}
}

func (c *storageReaderServiceClient) ListCurrency(ctx context.Context, in *ListCurrencyRequest, opts ...grpc.CallOption) (*ListCurrencyResponse, error) {
	out := new(ListCurrencyResponse)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/ListCurrency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) GetCurrency(ctx context.Context, in *GetCurrencyRequest, opts ...grpc.CallOption) (*model.Currency, error) {
	out := new(model.Currency)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/GetCurrency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) ListRatesOfExchange(ctx context.Context, in *ListRatesOfExchangeRequest, opts ...grpc.CallOption) (*ListRatesOfExchangeResponse, error) {
	out := new(ListRatesOfExchangeResponse)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/ListRatesOfExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) GetRateOfExchange(ctx context.Context, in *GetRateOfExchangeRequest, opts ...grpc.CallOption) (*model.RateOfExchange, error) {
	out := new(model.RateOfExchange)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/GetRateOfExchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) ListLocations(ctx context.Context, in *ListLocationsRequest, opts ...grpc.CallOption) (*ListLocationsResponse, error) {
	out := new(ListLocationsResponse)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/ListLocations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) GetLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*model.Location, error) {
	out := new(model.Location)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/GetLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) ListProducts(ctx context.Context, in *ListProductsRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/ListProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*model.Product, error) {
	out := new(model.Product)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) ListPrices(ctx context.Context, in *ListPricesRequest, opts ...grpc.CallOption) (*ListPricesResponse, error) {
	out := new(ListPricesResponse)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/ListPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) GetPrice(ctx context.Context, in *GetPriceRequest, opts ...grpc.CallOption) (*model.Price, error) {
	out := new(model.Price)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/GetPrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) ListPositions(ctx context.Context, in *ListPositionsRequest, opts ...grpc.CallOption) (*ListPositionsResponse, error) {
	out := new(ListPositionsResponse)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/ListPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) GetPosition(ctx context.Context, in *GetPositionRequest, opts ...grpc.CallOption) (*model.Position, error) {
	out := new(model.Position)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/GetPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) ListEmployees(ctx context.Context, in *ListEmployeesRequest, opts ...grpc.CallOption) (*ListEmployeesResponse, error) {
	out := new(ListEmployeesResponse)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/ListEmployees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) GetEmployee(ctx context.Context, in *GetEmployeeRequest, opts ...grpc.CallOption) (*model.Employee, error) {
	out := new(model.Employee)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/GetEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) ListMethods(ctx context.Context, in *ListMethodsRequest, opts ...grpc.CallOption) (*ListMethodsResponse, error) {
	out := new(ListMethodsResponse)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/ListMethods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) GetMethod(ctx context.Context, in *GetMethodRequest, opts ...grpc.CallOption) (*model.Method, error) {
	out := new(model.Method)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/GetMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) ListReceipts(ctx context.Context, in *ListReceiptsRequest, opts ...grpc.CallOption) (*ListReceiptsResponse, error) {
	out := new(ListReceiptsResponse)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/ListReceipts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) GetReceipt(ctx context.Context, in *GetReceiptRequest, opts ...grpc.CallOption) (*model.Receipt, error) {
	out := new(model.Receipt)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/GetReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) ListPurchases(ctx context.Context, in *ListPurchasesRequest, opts ...grpc.CallOption) (*ListPurchasesResponse, error) {
	out := new(ListPurchasesResponse)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/ListPurchases", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReaderServiceClient) GetPurchase(ctx context.Context, in *GetPurchaseRequest, opts ...grpc.CallOption) (*model.Purchase, error) {
	out := new(model.Purchase)
	err := c.cc.Invoke(ctx, "/reader.StorageReaderService/GetPurchase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageReaderServiceServer is the server API for StorageReaderService service.
type StorageReaderServiceServer interface {
	ListCurrency(context.Context, *ListCurrencyRequest) (*ListCurrencyResponse, error)
	GetCurrency(context.Context, *GetCurrencyRequest) (*model.Currency, error)
	ListRatesOfExchange(context.Context, *ListRatesOfExchangeRequest) (*ListRatesOfExchangeResponse, error)
	GetRateOfExchange(context.Context, *GetRateOfExchangeRequest) (*model.RateOfExchange, error)
	ListLocations(context.Context, *ListLocationsRequest) (*ListLocationsResponse, error)
	GetLocation(context.Context, *GetLocationRequest) (*model.Location, error)
	ListProducts(context.Context, *ListProductsRequest) (*ListProductsResponse, error)
	GetProduct(context.Context, *GetProductRequest) (*model.Product, error)
	ListPrices(context.Context, *ListPricesRequest) (*ListPricesResponse, error)
	GetPrice(context.Context, *GetPriceRequest) (*model.Price, error)
	ListPositions(context.Context, *ListPositionsRequest) (*ListPositionsResponse, error)
	GetPosition(context.Context, *GetPositionRequest) (*model.Position, error)
	ListEmployees(context.Context, *ListEmployeesRequest) (*ListEmployeesResponse, error)
	GetEmployee(context.Context, *GetEmployeeRequest) (*model.Employee, error)
	ListMethods(context.Context, *ListMethodsRequest) (*ListMethodsResponse, error)
	GetMethod(context.Context, *GetMethodRequest) (*model.Method, error)
	ListReceipts(context.Context, *ListReceiptsRequest) (*ListReceiptsResponse, error)
	GetReceipt(context.Context, *GetReceiptRequest) (*model.Receipt, error)
	ListPurchases(context.Context, *ListPurchasesRequest) (*ListPurchasesResponse, error)
	GetPurchase(context.Context, *GetPurchaseRequest) (*model.Purchase, error)
}

// UnimplementedStorageReaderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStorageReaderServiceServer struct {
}

func (*UnimplementedStorageReaderServiceServer) ListCurrency(ctx context.Context, req *ListCurrencyRequest) (*ListCurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCurrency not implemented")
}
func (*UnimplementedStorageReaderServiceServer) GetCurrency(ctx context.Context, req *GetCurrencyRequest) (*model.Currency, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrency not implemented")
}
func (*UnimplementedStorageReaderServiceServer) ListRatesOfExchange(ctx context.Context, req *ListRatesOfExchangeRequest) (*ListRatesOfExchangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRatesOfExchange not implemented")
}
func (*UnimplementedStorageReaderServiceServer) GetRateOfExchange(ctx context.Context, req *GetRateOfExchangeRequest) (*model.RateOfExchange, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRateOfExchange not implemented")
}
func (*UnimplementedStorageReaderServiceServer) ListLocations(ctx context.Context, req *ListLocationsRequest) (*ListLocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLocations not implemented")
}
func (*UnimplementedStorageReaderServiceServer) GetLocation(ctx context.Context, req *GetLocationRequest) (*model.Location, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocation not implemented")
}
func (*UnimplementedStorageReaderServiceServer) ListProducts(ctx context.Context, req *ListProductsRequest) (*ListProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (*UnimplementedStorageReaderServiceServer) GetProduct(ctx context.Context, req *GetProductRequest) (*model.Product, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (*UnimplementedStorageReaderServiceServer) ListPrices(ctx context.Context, req *ListPricesRequest) (*ListPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPrices not implemented")
}
func (*UnimplementedStorageReaderServiceServer) GetPrice(ctx context.Context, req *GetPriceRequest) (*model.Price, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrice not implemented")
}
func (*UnimplementedStorageReaderServiceServer) ListPositions(ctx context.Context, req *ListPositionsRequest) (*ListPositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPositions not implemented")
}
func (*UnimplementedStorageReaderServiceServer) GetPosition(ctx context.Context, req *GetPositionRequest) (*model.Position, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosition not implemented")
}
func (*UnimplementedStorageReaderServiceServer) ListEmployees(ctx context.Context, req *ListEmployeesRequest) (*ListEmployeesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEmployees not implemented")
}
func (*UnimplementedStorageReaderServiceServer) GetEmployee(ctx context.Context, req *GetEmployeeRequest) (*model.Employee, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployee not implemented")
}
func (*UnimplementedStorageReaderServiceServer) ListMethods(ctx context.Context, req *ListMethodsRequest) (*ListMethodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMethods not implemented")
}
func (*UnimplementedStorageReaderServiceServer) GetMethod(ctx context.Context, req *GetMethodRequest) (*model.Method, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMethod not implemented")
}
func (*UnimplementedStorageReaderServiceServer) ListReceipts(ctx context.Context, req *ListReceiptsRequest) (*ListReceiptsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListReceipts not implemented")
}
func (*UnimplementedStorageReaderServiceServer) GetReceipt(ctx context.Context, req *GetReceiptRequest) (*model.Receipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReceipt not implemented")
}
func (*UnimplementedStorageReaderServiceServer) ListPurchases(ctx context.Context, req *ListPurchasesRequest) (*ListPurchasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPurchases not implemented")
}
func (*UnimplementedStorageReaderServiceServer) GetPurchase(ctx context.Context, req *GetPurchaseRequest) (*model.Purchase, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPurchase not implemented")
}

func RegisterStorageReaderServiceServer(s *grpc.Server, srv StorageReaderServiceServer) {
	s.RegisterService(&_StorageReaderService_serviceDesc, srv)
}

func _StorageReaderService_ListCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).ListCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/ListCurrency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).ListCurrency(ctx, req.(*ListCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_GetCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).GetCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/GetCurrency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).GetCurrency(ctx, req.(*GetCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_ListRatesOfExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRatesOfExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).ListRatesOfExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/ListRatesOfExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).ListRatesOfExchange(ctx, req.(*ListRatesOfExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_GetRateOfExchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRateOfExchangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).GetRateOfExchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/GetRateOfExchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).GetRateOfExchange(ctx, req.(*GetRateOfExchangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_ListLocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).ListLocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/ListLocations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).ListLocations(ctx, req.(*ListLocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_GetLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).GetLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/GetLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).GetLocation(ctx, req.(*GetLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/ListProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).ListProducts(ctx, req.(*ListProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_ListPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).ListPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/ListPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).ListPrices(ctx, req.(*ListPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_GetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).GetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/GetPrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).GetPrice(ctx, req.(*GetPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_ListPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).ListPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/ListPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).ListPositions(ctx, req.(*ListPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_GetPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).GetPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/GetPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).GetPosition(ctx, req.(*GetPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_ListEmployees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEmployeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).ListEmployees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/ListEmployees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).ListEmployees(ctx, req.(*ListEmployeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_GetEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).GetEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/GetEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).GetEmployee(ctx, req.(*GetEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_ListMethods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMethodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).ListMethods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/ListMethods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).ListMethods(ctx, req.(*ListMethodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_GetMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).GetMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/GetMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).GetMethod(ctx, req.(*GetMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_ListReceipts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReceiptsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).ListReceipts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/ListReceipts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).ListReceipts(ctx, req.(*ListReceiptsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_GetReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).GetReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/GetReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).GetReceipt(ctx, req.(*GetReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_ListPurchases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPurchasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).ListPurchases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/ListPurchases",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).ListPurchases(ctx, req.(*ListPurchasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageReaderService_GetPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReaderServiceServer).GetPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reader.StorageReaderService/GetPurchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReaderServiceServer).GetPurchase(ctx, req.(*GetPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageReaderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "reader.StorageReaderService",
	HandlerType: (*StorageReaderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCurrency",
			Handler:    _StorageReaderService_ListCurrency_Handler,
		},
		{
			MethodName: "GetCurrency",
			Handler:    _StorageReaderService_GetCurrency_Handler,
		},
		{
			MethodName: "ListRatesOfExchange",
			Handler:    _StorageReaderService_ListRatesOfExchange_Handler,
		},
		{
			MethodName: "GetRateOfExchange",
			Handler:    _StorageReaderService_GetRateOfExchange_Handler,
		},
		{
			MethodName: "ListLocations",
			Handler:    _StorageReaderService_ListLocations_Handler,
		},
		{
			MethodName: "GetLocation",
			Handler:    _StorageReaderService_GetLocation_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _StorageReaderService_ListProducts_Handler,
		},
		{
			MethodName: "GetProduct",
			Handler:    _StorageReaderService_GetProduct_Handler,
		},
		{
			MethodName: "ListPrices",
			Handler:    _StorageReaderService_ListPrices_Handler,
		},
		{
			MethodName: "GetPrice",
			Handler:    _StorageReaderService_GetPrice_Handler,
		},
		{
			MethodName: "ListPositions",
			Handler:    _StorageReaderService_ListPositions_Handler,
		},
		{
			MethodName: "GetPosition",
			Handler:    _StorageReaderService_GetPosition_Handler,
		},
		{
			MethodName: "ListEmployees",
			Handler:    _StorageReaderService_ListEmployees_Handler,
		},
		{
			MethodName: "GetEmployee",
			Handler:    _StorageReaderService_GetEmployee_Handler,
		},
		{
			MethodName: "ListMethods",
			Handler:    _StorageReaderService_ListMethods_Handler,
		},
		{
			MethodName: "GetMethod",
			Handler:    _StorageReaderService_GetMethod_Handler,
		},
		{
			MethodName: "ListReceipts",
			Handler:    _StorageReaderService_ListReceipts_Handler,
		},
		{
			MethodName: "GetReceipt",
			Handler:    _StorageReaderService_GetReceipt_Handler,
		},
		{
			MethodName: "ListPurchases",
			Handler:    _StorageReaderService_ListPurchases_Handler,
		},
		{
			MethodName: "GetPurchase",
			Handler:    _StorageReaderService_GetPurchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reader/reader.proto",
}
