// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/analytics/analytics.proto

package analytics

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PricesStat struct {
	Id                   uint32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Revenues             []float32 `protobuf:"fixed32,2,rep,packed,name=revenues,proto3" json:"revenues,omitempty"`
	Sum                  float32   `protobuf:"fixed32,3,opt,name=sum,proto3" json:"sum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PricesStat) Reset()         { *m = PricesStat{} }
func (m *PricesStat) String() string { return proto.CompactTextString(m) }
func (*PricesStat) ProtoMessage()    {}
func (*PricesStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb2a98f65dc1200, []int{0}
}

func (m *PricesStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PricesStat.Unmarshal(m, b)
}
func (m *PricesStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PricesStat.Marshal(b, m, deterministic)
}
func (m *PricesStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PricesStat.Merge(m, src)
}
func (m *PricesStat) XXX_Size() int {
	return xxx_messageInfo_PricesStat.Size(m)
}
func (m *PricesStat) XXX_DiscardUnknown() {
	xxx_messageInfo_PricesStat.DiscardUnknown(m)
}

var xxx_messageInfo_PricesStat proto.InternalMessageInfo

func (m *PricesStat) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PricesStat) GetRevenues() []float32 {
	if m != nil {
		return m.Revenues
	}
	return nil
}

func (m *PricesStat) GetSum() float32 {
	if m != nil {
		return m.Sum
	}
	return 0
}

type GetABCByPricesRequest struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetABCByPricesRequest) Reset()         { *m = GetABCByPricesRequest{} }
func (m *GetABCByPricesRequest) String() string { return proto.CompactTextString(m) }
func (*GetABCByPricesRequest) ProtoMessage()    {}
func (*GetABCByPricesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb2a98f65dc1200, []int{1}
}

func (m *GetABCByPricesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetABCByPricesRequest.Unmarshal(m, b)
}
func (m *GetABCByPricesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetABCByPricesRequest.Marshal(b, m, deterministic)
}
func (m *GetABCByPricesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetABCByPricesRequest.Merge(m, src)
}
func (m *GetABCByPricesRequest) XXX_Size() int {
	return xxx_messageInfo_GetABCByPricesRequest.Size(m)
}
func (m *GetABCByPricesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetABCByPricesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetABCByPricesRequest proto.InternalMessageInfo

func (m *GetABCByPricesRequest) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

type GetABCByPricesResponse struct {
	Ids                  []uint32 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	ABC                  []string `protobuf:"bytes,2,rep,name=ABC,proto3" json:"ABC,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetABCByPricesResponse) Reset()         { *m = GetABCByPricesResponse{} }
func (m *GetABCByPricesResponse) String() string { return proto.CompactTextString(m) }
func (*GetABCByPricesResponse) ProtoMessage()    {}
func (*GetABCByPricesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7fb2a98f65dc1200, []int{2}
}

func (m *GetABCByPricesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetABCByPricesResponse.Unmarshal(m, b)
}
func (m *GetABCByPricesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetABCByPricesResponse.Marshal(b, m, deterministic)
}
func (m *GetABCByPricesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetABCByPricesResponse.Merge(m, src)
}
func (m *GetABCByPricesResponse) XXX_Size() int {
	return xxx_messageInfo_GetABCByPricesResponse.Size(m)
}
func (m *GetABCByPricesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetABCByPricesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetABCByPricesResponse proto.InternalMessageInfo

func (m *GetABCByPricesResponse) GetIds() []uint32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *GetABCByPricesResponse) GetABC() []string {
	if m != nil {
		return m.ABC
	}
	return nil
}

func init() {
	proto.RegisterType((*PricesStat)(nil), "analytics.PricesStat")
	proto.RegisterType((*GetABCByPricesRequest)(nil), "analytics.GetABCByPricesRequest")
	proto.RegisterType((*GetABCByPricesResponse)(nil), "analytics.GetABCByPricesResponse")
}

func init() { proto.RegisterFile("proto/analytics/analytics.proto", fileDescriptor_7fb2a98f65dc1200) }

var fileDescriptor_7fb2a98f65dc1200 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xdd, 0xac, 0x8a, 0x1d, 0x68, 0x29, 0x03, 0x4a, 0xe8, 0xc5, 0x98, 0x53, 0x40, 0xa8,
	0xa0, 0x57, 0x2f, 0xbb, 0x3d, 0x08, 0x9e, 0x24, 0x3d, 0x78, 0x8e, 0xbb, 0x73, 0x08, 0xea, 0x6e,
	0xcd, 0x64, 0x0b, 0xfb, 0xef, 0x25, 0x29, 0xb6, 0x28, 0xd2, 0xdb, 0x97, 0xc9, 0xf0, 0xf1, 0xde,
	0xc0, 0xf5, 0x26, 0xf4, 0xb1, 0xbf, 0x73, 0x9d, 0xfb, 0x18, 0xa3, 0x6f, 0xf8, 0x40, 0xcb, 0xfc,
	0x83, 0x93, 0xfd, 0x40, 0x3f, 0x03, 0xbc, 0x04, 0xdf, 0x10, 0xaf, 0xa3, 0x8b, 0x38, 0x03, 0xe1,
	0x5b, 0x59, 0xa8, 0xc2, 0x4c, 0xad, 0xf0, 0x2d, 0x2e, 0xe0, 0x22, 0xd0, 0x96, 0xba, 0x81, 0x58,
	0x0a, 0x55, 0x1a, 0x61, 0xf7, 0x6f, 0x9c, 0x43, 0xc9, 0xc3, 0xa7, 0x2c, 0x55, 0x61, 0x84, 0x4d,
	0xa8, 0x6f, 0xe1, 0xf2, 0x89, 0x62, 0x55, 0xaf, 0xea, 0x71, 0xe7, 0xb4, 0xf4, 0x35, 0x10, 0x47,
	0x44, 0x38, 0x1d, 0xc9, 0x85, 0x2c, 0x3e, 0xb3, 0x99, 0xf5, 0x23, 0x5c, 0xfd, 0x5d, 0xe6, 0x4d,
	0xdf, 0x31, 0x25, 0xb1, 0x6f, 0x59, 0x16, 0xaa, 0x34, 0x53, 0x9b, 0x30, 0x4d, 0xaa, 0x7a, 0x95,
	0x13, 0x4c, 0x6c, 0xc2, 0xfb, 0x77, 0x98, 0x57, 0x3f, 0x1d, 0xd6, 0x14, 0xb6, 0xbe, 0x21, 0x7c,
	0x85, 0xd9, 0x6f, 0x23, 0xaa, 0xe5, 0xa1, 0xf9, 0xbf, 0xc9, 0x16, 0x37, 0x47, 0x36, 0x76, 0x71,
	0xf4, 0xc9, 0xdb, 0x79, 0xbe, 0xda, 0xc3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbd, 0xee, 0xa5,
	0x40, 0x58, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetABCByPrices(ctx context.Context, in *GetABCByPricesRequest, opts ...grpc.CallOption) (*GetABCByPricesResponse, error)
}

type analyticsServiceClient struct {
	cc *grpc.ClientConn
}

func NewAnalyticsServiceClient(cc *grpc.ClientConn) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetABCByPrices(ctx context.Context, in *GetABCByPricesRequest, opts ...grpc.CallOption) (*GetABCByPricesResponse, error) {
	out := new(GetABCByPricesResponse)
	err := c.cc.Invoke(ctx, "/analytics.AnalyticsService/GetABCByPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
type AnalyticsServiceServer interface {
	GetABCByPrices(context.Context, *GetABCByPricesRequest) (*GetABCByPricesResponse, error)
}

// UnimplementedAnalyticsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAnalyticsServiceServer struct {
}

func (*UnimplementedAnalyticsServiceServer) GetABCByPrices(ctx context.Context, req *GetABCByPricesRequest) (*GetABCByPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetABCByPrices not implemented")
}

func RegisterAnalyticsServiceServer(s *grpc.Server, srv AnalyticsServiceServer) {
	s.RegisterService(&_AnalyticsService_serviceDesc, srv)
}

func _AnalyticsService_GetABCByPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetABCByPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetABCByPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/analytics.AnalyticsService/GetABCByPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetABCByPrices(ctx, req.(*GetABCByPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnalyticsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetABCByPrices",
			Handler:    _AnalyticsService_GetABCByPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/analytics/analytics.proto",
}
